//! Parser-owned registry of accepted `PostgreSQL` command identities.

macro_rules! command_identities {
    ($(($variant:ident, $name:literal)),+ $(,)?) => {
        #[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
        pub enum CommandIdentity { $( $variant, )+ }
        impl CommandIdentity {
            pub const ALL: &[Self] = &[ $( Self::$variant, )+ ];
            #[must_use]
            pub const fn name(self) -> &'static str { match self { $( Self::$variant => $name, )+ } }
        }
    };
}

command_identities!(
    (Abort, "ABORT"),
    (AlterConversion, "ALTER CONVERSION"),
    (AlterDatabase, "ALTER DATABASE"),
    (AlterDomain, "ALTER DOMAIN"),
    (AlterEventTrigger, "ALTER EVENT TRIGGER"),
    (AlterExtension, "ALTER EXTENSION"),
    (AlterFunction, "ALTER FUNCTION"),
    (AlterLanguage, "ALTER LANGUAGE"),
    (AlterLargeObject, "ALTER LARGE OBJECT"),
    (AlterOperator, "ALTER OPERATOR"),
    (AlterOperatorClass, "ALTER OPERATOR CLASS"),
    (AlterOperatorFamily, "ALTER OPERATOR FAMILY"),
    (AlterProcedure, "ALTER PROCEDURE"),
    (AlterPublication, "ALTER PUBLICATION"),
    (AlterRoutine, "ALTER ROUTINE"),
    (AlterRule, "ALTER RULE"),
    (AlterSchema, "ALTER SCHEMA"),
    (AlterServer, "ALTER SERVER"),
    (AlterStatistics, "ALTER STATISTICS"),
    (AlterSubscription, "ALTER SUBSCRIPTION"),
    (AlterSystem, "ALTER SYSTEM"),
    (AlterTable, "ALTER TABLE"),
    (AlterTablespace, "ALTER TABLESPACE"),
    (
        AlterTextSearchConfiguration,
        "ALTER TEXT SEARCH CONFIGURATION"
    ),
    (AlterTextSearchDictionary, "ALTER TEXT SEARCH DICTIONARY"),
    (AlterTextSearchParser, "ALTER TEXT SEARCH PARSER"),
    (AlterTextSearchTemplate, "ALTER TEXT SEARCH TEMPLATE"),
    (AlterTrigger, "ALTER TRIGGER"),
    (AlterType, "ALTER TYPE"),
    (AlterUserMapping, "ALTER USER MAPPING"),
    (Analyze, "ANALYZE"),
    (Begin, "BEGIN"),
    (Call, "CALL"),
    (Checkpoint, "CHECKPOINT"),
    (Close, "CLOSE"),
    (Cluster, "CLUSTER"),
    (Comment, "COMMENT"),
    (Commit, "COMMIT"),
    (CommitPrepared, "COMMIT PREPARED"),
    (Copy, "COPY"),
    (CreateAccessMethod, "CREATE ACCESS METHOD"),
    (CreateConversion, "CREATE CONVERSION"),
    (CreateDatabase, "CREATE DATABASE"),
    (CreateDomain, "CREATE DOMAIN"),
    (CreateEventTrigger, "CREATE EVENT TRIGGER"),
    (CreateForeignDataWrapper, "CREATE FOREIGN DATA WRAPPER"),
    (CreateForeignTable, "CREATE FOREIGN TABLE"),
    (CreateFunction, "CREATE FUNCTION"),
    (CreateIndex, "CREATE INDEX"),
    (CreateLanguage, "CREATE LANGUAGE"),
    (CreateOperator, "CREATE OPERATOR"),
    (CreateOperatorClass, "CREATE OPERATOR CLASS"),
    (CreateOperatorFamily, "CREATE OPERATOR FAMILY"),
    (CreateProcedure, "CREATE PROCEDURE"),
    (CreatePublication, "CREATE PUBLICATION"),
    (CreateRole, "CREATE ROLE"),
    (CreateRule, "CREATE RULE"),
    (CreateSchema, "CREATE SCHEMA"),
    (CreateSequence, "CREATE SEQUENCE"),
    (CreateServer, "CREATE SERVER"),
    (CreateStatistics, "CREATE STATISTICS"),
    (CreateSubscription, "CREATE SUBSCRIPTION"),
    (CreateTable, "CREATE TABLE"),
    (CreateTableAs, "CREATE TABLE AS"),
    (CreateTablespace, "CREATE TABLESPACE"),
    (
        CreateTextSearchConfiguration,
        "CREATE TEXT SEARCH CONFIGURATION"
    ),
    (CreateTextSearchDictionary, "CREATE TEXT SEARCH DICTIONARY"),
    (CreateTextSearchParser, "CREATE TEXT SEARCH PARSER"),
    (CreateTextSearchTemplate, "CREATE TEXT SEARCH TEMPLATE"),
    (CreateTransform, "CREATE TRANSFORM"),
    (CreateTrigger, "CREATE TRIGGER"),
    (CreateType, "CREATE TYPE"),
    (CreateUser, "CREATE USER"),
    (CreateUserMapping, "CREATE USER MAPPING"),
    (CreateView, "CREATE VIEW"),
    (Deallocate, "DEALLOCATE"),
    (Declare, "DECLARE"),
    (Delete, "DELETE"),
    (Discard, "DISCARD"),
    (Do, "DO"),
    (DropAccessMethod, "DROP ACCESS METHOD"),
    (DropConversion, "DROP CONVERSION"),
    (DropDatabase, "DROP DATABASE"),
    (DropDomain, "DROP DOMAIN"),
    (DropEventTrigger, "DROP EVENT TRIGGER"),
    (DropExtension, "DROP EXTENSION"),
    (DropForeignDataWrapper, "DROP FOREIGN DATA WRAPPER"),
    (DropForeignTable, "DROP FOREIGN TABLE"),
    (DropFunction, "DROP FUNCTION"),
    (DropIndex, "DROP INDEX"),
    (DropLanguage, "DROP LANGUAGE"),
    (DropOperator, "DROP OPERATOR"),
    (DropOperatorClass, "DROP OPERATOR CLASS"),
    (DropOperatorFamily, "DROP OPERATOR FAMILY"),
    (DropProcedure, "DROP PROCEDURE"),
    (DropPublication, "DROP PUBLICATION"),
    (DropRole, "DROP ROLE"),
    (DropRoutine, "DROP ROUTINE"),
    (DropRule, "DROP RULE"),
    (DropSchema, "DROP SCHEMA"),
    (DropSequence, "DROP SEQUENCE"),
    (DropServer, "DROP SERVER"),
    (DropStatistics, "DROP STATISTICS"),
    (DropSubscription, "DROP SUBSCRIPTION"),
    (DropTable, "DROP TABLE"),
    (DropTablespace, "DROP TABLESPACE"),
    (
        DropTextSearchConfiguration,
        "DROP TEXT SEARCH CONFIGURATION"
    ),
    (DropTextSearchDictionary, "DROP TEXT SEARCH DICTIONARY"),
    (DropTextSearchParser, "DROP TEXT SEARCH PARSER"),
    (DropTextSearchTemplate, "DROP TEXT SEARCH TEMPLATE"),
    (DropTransform, "DROP TRANSFORM"),
    (DropTrigger, "DROP TRIGGER"),
    (DropType, "DROP TYPE"),
    (DropUser, "DROP USER"),
    (DropUserMapping, "DROP USER MAPPING"),
    (DropView, "DROP VIEW"),
    (End, "END"),
    (Execute, "EXECUTE"),
    (Explain, "EXPLAIN"),
    (Fetch, "FETCH"),
    (Grant, "GRANT"),
    (ImportForeignSchema, "IMPORT FOREIGN SCHEMA"),
    (Insert, "INSERT"),
    (Listen, "LISTEN"),
    (Load, "LOAD"),
    (Lock, "LOCK"),
    (Merge, "MERGE"),
    (Move, "MOVE"),
    (Notify, "NOTIFY"),
    (Prepare, "PREPARE"),
    (PrepareTransaction, "PREPARE TRANSACTION"),
    (Reindex, "REINDEX"),
    (ReleaseSavepoint, "RELEASE SAVEPOINT"),
    (Reset, "RESET"),
    (Revoke, "REVOKE"),
    (Rollback, "ROLLBACK"),
    (RollbackPrepared, "ROLLBACK PREPARED"),
    (RollbackToSavepoint, "ROLLBACK TO SAVEPOINT"),
    (Savepoint, "SAVEPOINT"),
    (SecurityLabel, "SECURITY LABEL"),
    (Select, "SELECT"),
    (SelectInto, "SELECT INTO"),
    (Set, "SET"),
    (SetConstraints, "SET CONSTRAINTS"),
    (SetRole, "SET ROLE"),
    (SetSessionAuthorization, "SET SESSION AUTHORIZATION"),
    (SetTransaction, "SET TRANSACTION"),
    (Show, "SHOW"),
    (StartTransaction, "START TRANSACTION"),
    (Table, "TABLE"),
    (Truncate, "TRUNCATE"),
    (Unlisten, "UNLISTEN"),
    (Update, "UPDATE"),
    (Vacuum, "VACUUM"),
    (Values, "VALUES"),
);
