//! The `ApiKey` enum, built as a `proc_macro2` token stream via `quote!`
//! instead of hand-written `write!` string templating.
//!
//! Compare with `api_key_enum::emit`. The structural payload — which variants,
//! discriminants, doc text — is identical; only the *emission mechanism*
//! differs. Things to notice:
//!
//! * No manual brace/indent bookkeeping. The `quote!` block reads like the
//!   target code; repetition is `#(#variants)*` instead of a `for` loop that
//!   `writeln!`s fragments.
//! * `syn::parse2` validates the output is real Rust *at generation time*. A
//!   malformed template fails here with a parse error, not three crates
//!   downstream when the generated file is compiled.
//! * `emit` returns the raw token string; the `rustfmt` pass in `crate::fmt`
//!   (run by the regeneration binary) does the formatting.
//!
//! The one wart: `//`-style line comments aren't tokens, so the
//! `// AUTO-GENERATED` banner is prepended as a string. Doc comments become
//! `#[doc = "…"]` attributes; rustfmt keeps them in that form (it does not
//! rewrite them to `///` without the unstable `normalize_doc_attributes`).

use std::collections::BTreeMap;

use proc_macro2::Literal;
use quote::{format_ident, quote};

use crate::ir::{MessageSpec, MessageType};

#[must_use]
/// # Panics
/// Panics if the validated schema model cannot be represented as the expected Rust syntax tree.
pub fn emit(specs: &[MessageSpec], schemas_version: &str) -> String {
    // Identical selection logic to api_key_enum::emit.
    let mut by_key: BTreeMap<i16, &MessageSpec> = BTreeMap::new();
    for s in specs {
        if matches!(s.message_type, MessageType::Request)
            && let Some(k) = s.api_key
            && !s.valid_versions.is_empty()
        {
            by_key.insert(k, s);
        }
    }

    let variants = by_key.iter().map(|(k, s)| {
        let pascal = s.name.trim_end_matches("Request");
        let ident = format_ident!("{pascal}");
        let disc = Literal::i16_unsuffixed(*k);
        let r = s.valid_versions;
        let max = if r.max == i16::MAX {
            String::from("\u{221e}")
        } else {
            r.max.to_string()
        };
        let doc = format!(
            " `{pascal}Request` (versions {min}\u{2013}{max}).",
            min = r.min
        );
        quote! {
            #[doc = #doc]
            #ident = #disc,
        }
    });

    let all_entries = by_key.values().map(|s| {
        let ident = format_ident!("{}", s.name.trim_end_matches("Request"));
        quote!(ApiKey::#ident,)
    });

    let match_arms = by_key.iter().map(|(k, s)| {
        let ident = format_ident!("{}", s.name.trim_end_matches("Request"));
        let lit = Literal::i16_unsuffixed(*k);
        quote!(#lit => Some(ApiKey::#ident),)
    });

    let tokens = quote! {
        #[doc = " Kafka API key registry generated from the vendored schemas."]
        #[doc = ""]
        #[doc = " Each variant corresponds to a request/response pair defined in the schemas."]
        #[doc = " Variants with `validVersions = \"none\"` are omitted (reserved keys with no"]
        #[doc = " currently-valid wire version)."]
        #[doc = ""]
        #[doc = " The enum is `#[non_exhaustive]` so that adding variants for new Kafka API"]
        #[doc = " keys in future schema updates is non-breaking."]
        #[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, strum::IntoStaticStr)]
        #[repr(i16)]
        #[non_exhaustive]
        pub enum ApiKey {
            #(#variants)*
        }

        impl ApiKey {
            #[doc = " All known API keys, in ascending numeric order."]
            pub const ALL: &'static [ApiKey] = &[
                #(#all_entries)*
            ];

            #[doc = " Resolve from numeric key; returns `None` for unknown keys."]
            pub fn from_i16(k: i16) -> Option<ApiKey> {
                match k {
                    #(#match_arms)*
                    _ => None,
                }
            }
        }
    };

    // Validate at generation time; rustfmt (applied by the caller) does the
    // actual formatting. See `crate::fmt`.
    let _validate: syn::File =
        syn::parse2(tokens.clone()).expect("generated ApiKey enum must be valid Rust");
    let banner = format!(
        "// AUTO-GENERATED by crabka-protocol-codegen against {schemas_version}. Do not edit.\n\
         // To regenerate: ./tools/regenerate.sh\n\n"
    );
    format!("{banner}{tokens}")
}
