//! Emit the central `ApiKey` enum mapping API key integers to symbolic names.

use std::collections::BTreeMap;
use std::fmt::Write;

use crate::ir::{MessageSpec, MessageType};

#[must_use]
pub fn emit(specs: &[MessageSpec], schemas_version: &str) -> String {
    // Build (api_key, name) map from request specs.
    // Skip specs with validVersions "none" (min > max) — those API keys have
    // been removed/reserved and no valid version exists, so emitting a variant
    // would produce an unreachable discriminant.
    let mut by_key: BTreeMap<i16, &MessageSpec> = BTreeMap::new();
    for s in specs {
        if matches!(s.message_type, MessageType::Request)
            && let Some(k) = s.api_key
            && !s.valid_versions.is_empty()
        {
            by_key.insert(k, s);
        }
    }

    let mut out = format!(
        "// AUTO-GENERATED by crabka-protocol-codegen against {schemas_version}. Do not edit.\n\
         // To regenerate: ./tools/regenerate.sh\n\n"
    );
    writeln!(
        out,
        "/// Kafka API key registry generated from the vendored schemas.\n\
         ///\n\
         /// Each variant corresponds to a request/response pair defined in the schemas.\n\
         /// Variants with `validVersions = \"none\"` are omitted (reserved keys with no\n\
         /// currently-valid wire version).\n\
         ///\n\
         /// The enum is `#[non_exhaustive]` so that adding variants for new Kafka API\n\
         /// keys in future schema updates is non-breaking."
    )
    .unwrap();
    writeln!(
        out,
        "#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, strum::IntoStaticStr)]"
    )
    .unwrap();
    writeln!(out, "#[repr(i16)]").unwrap();
    writeln!(out, "#[non_exhaustive]").unwrap();
    writeln!(out, "pub enum ApiKey {{").unwrap();
    for (k, s) in &by_key {
        let pascal = s.name.trim_end_matches("Request");
        let r = s.valid_versions;
        writeln!(
            out,
            "    /// `{pascal}Request` (versions {min}–{max}).\n    {pascal} = {k},",
            min = r.min,
            max = if r.max == i16::MAX {
                String::from("\u{221e}")
            } else {
                r.max.to_string()
            },
        )
        .unwrap();
    }
    writeln!(out, "}}").unwrap();

    writeln!(
        out,
        "
impl ApiKey {{
    /// All known API keys, in ascending numeric order.
    pub const ALL: &'static [ApiKey] = &["
    )
    .unwrap();
    for s in by_key.values() {
        let pascal = s.name.trim_end_matches("Request");
        writeln!(out, "        ApiKey::{pascal},").unwrap();
    }
    writeln!(
        out,
        "    ];

    /// Resolve from numeric key; returns `None` for unknown keys.
    pub fn from_i16(k: i16) -> Option<ApiKey> {{
        match k {{"
    )
    .unwrap();
    for (k, s) in &by_key {
        let pascal = s.name.trim_end_matches("Request");
        writeln!(out, "            {k} => Some(ApiKey::{pascal}),").unwrap();
    }
    writeln!(
        out,
        "            _ => None,
        }}
    }}
}}"
    )
    .unwrap();
    out
}
