/// Return the standard AUTO-GENERATED header comment for a generated source file.
#[must_use]
pub fn banner(schemas_version: &str) -> String {
    format!(
        "// AUTO-GENERATED by crabka-protocol-codegen against {schemas_version}. Do not edit.\n"
    )
}

/// Format an integer string as a Rust literal with underscores every 3 digits from the right,
/// satisfying `clippy::unreadable_literal` for large numbers (e.g., `-2_147_483_648i32`).
///
/// Handles hex literals (`0x...`) by parsing them to decimal first so we emit clean decimal
/// literals (e.g. `"0x7fffffff"` → `2_147_483_647i32`).
#[must_use]
pub fn format_int_literal(s: &str, suffix: &str) -> String {
    // Normalise hex literals to decimal so we don't produce malformed output
    // like `0_x7f_fff_fffi32`.
    let (negative_in, s) = if let Some(rest) = s.strip_prefix('-') {
        (true, rest)
    } else {
        (false, s)
    };
    let s = s.trim();
    // Try to parse as hex; on failure fall through and treat as decimal string.
    let decimal_string: String;
    let (negative, digits): (bool, &str) =
        if let Some(hex) = s.strip_prefix("0x").or_else(|| s.strip_prefix("0X")) {
            // Parse the hex digits as u64 then reinterpret the bits at the target
            // type's width. A 32-bit constant like `0xffffffff` for an `i32` field
            // means -1, not 4_294_967_295 (which would overflow the literal).
            if let Ok(v) = u64::from_str_radix(hex, 16) {
                let signed = hex_to_signed(v, suffix);
                if negative_in || signed < 0 {
                    decimal_string = format!("{}", signed.unsigned_abs());
                    (true, &decimal_string)
                } else {
                    decimal_string = format!("{signed}");
                    (false, &decimal_string)
                }
            } else {
                // Fallback: keep the hex string as-is (should not happen with valid schemas).
                decimal_string = s.to_string();
                (negative_in, &decimal_string)
            }
        } else {
            decimal_string = s.to_string();
            (negative_in, &decimal_string)
        };
    #[allow(clippy::manual_is_multiple_of)]
    let underscored: String = {
        let chars: Vec<char> = digits.chars().collect();
        let mut result = String::new();
        let len = chars.len();
        for (i, &c) in chars.iter().enumerate() {
            if i > 0 && (len - i) % 3 == 0 {
                result.push('_');
            }
            result.push(c);
        }
        result
    };
    if negative {
        format!("-{underscored}{suffix}")
    } else {
        format!("{underscored}{suffix}")
    }
}

/// Reinterpret the bits of a hex literal at the width of its Rust type suffix
/// (e.g. `"i32"`, `"i64"`). For a signed suffix the top bit of that width sign-
/// extends, so `0xffffffff` with `"i32"` yields `-1`. Unsigned suffixes and
/// 64-bit widths are returned unchanged.
fn hex_to_signed(v: u64, suffix: &str) -> i64 {
    let bits: u32 = suffix.trim_start_matches(['i', 'u']).parse().unwrap_or(64);
    if bits >= 64 {
        #[allow(clippy::cast_possible_wrap)]
        return v as i64;
    }
    let mask = (1u64 << bits) - 1;
    let x = v & mask;
    #[allow(clippy::cast_possible_wrap)]
    if suffix.starts_with('i') && (x & (1u64 << (bits - 1))) != 0 {
        (x as i64) - (1i64 << bits)
    } else {
        x as i64
    }
}

#[cfg(test)]
mod tests {

    use super::*;

    #[test]
    fn decimal_literals() {
        for (input, want) in [
            ("0", "0i32"),
            ("-1", "-1i32"),
            ("2147483647", "2_147_483_647i32"),
            ("-2147483648", "-2_147_483_648i32"),
        ] {
            assert2::assert!(format_int_literal(input, "i32") == want);
        }
    }

    #[test]
    fn hex_positive_normalizes_to_decimal() {
        for (_case, input, want) in [
            ("lowercase", "0x7fffffff", "2_147_483_647i32"),
            ("uppercase", "0X10", "16i32"),
        ] {
            assert2::assert!(format_int_literal(input, "i32") == want);
        }
    }

    #[test]
    fn hex_high_bit_is_sign_extended_to_target_width() {
        // 0xffffffff as i32 is -1, not 4_294_967_295 (which would overflow i32).
        // The same 32-bit pattern widened to i64 is a large positive value.
        for (input, suffix, want) in [
            ("0xffffffff", "i32", "-1i32"),
            ("0x80000000", "i32", "-2_147_483_648i32"),
            ("0xffffffff", "i64", "4_294_967_295i64"),
        ] {
            assert2::assert!(format_int_literal(input, suffix) == want);
        }
    }
}
