/// Return the standard AUTO-GENERATED header comment for a generated source file.
#[must_use]
pub fn banner(schemas_version: &str) -> String {
    format!(
        "// AUTO-GENERATED by crabka-protocol-codegen against {schemas_version}. Do not edit.\n"
    )
}

/// Format an integer string as a Rust literal with underscores every 3 digits from the right,
/// satisfying `clippy::unreadable_literal` for large numbers (e.g., `-2_147_483_648i32`).
///
/// Handles hex literals (`0x...`) by parsing them to decimal first so we emit clean decimal
/// literals (e.g. `"0x7fffffff"` → `2_147_483_647i32`).
#[must_use]
pub fn format_int_literal(s: &str, suffix: &str) -> String {
    // Normalise hex literals to decimal so we don't produce malformed output
    // like `0_x7f_fff_fffi32`.
    let (negative_in, s) = if let Some(rest) = s.strip_prefix('-') {
        (true, rest)
    } else {
        (false, s)
    };
    let s = s.trim();
    // Try to parse as hex; on failure fall through and treat as decimal string.
    let decimal_string: String;
    let (negative, digits): (bool, &str) = if let Some(hex) = s.strip_prefix("0x").or_else(|| s.strip_prefix("0X")) {
        // Parse the hex digits as u64 then convert to signed decimal.
        if let Ok(v) = u64::from_str_radix(hex, 16) {
            let signed = v as i64;
            if negative_in || signed < 0 {
                decimal_string = format!("{}", signed.unsigned_abs());
                (true, &decimal_string)
            } else {
                decimal_string = format!("{signed}");
                (false, &decimal_string)
            }
        } else {
            // Fallback: keep the hex string as-is (should not happen with valid schemas).
            decimal_string = s.to_string();
            (negative_in, &decimal_string)
        }
    } else {
        decimal_string = s.to_string();
        (negative_in, &decimal_string)
    };
    #[allow(clippy::manual_is_multiple_of)]
    let underscored: String = {
        let chars: Vec<char> = digits.chars().collect();
        let mut result = String::new();
        let len = chars.len();
        for (i, &c) in chars.iter().enumerate() {
            if i > 0 && (len - i) % 3 == 0 {
                result.push('_');
            }
            result.push(c);
        }
        result
    };
    if negative {
        format!("-{underscored}{suffix}")
    } else {
        format!("{underscored}{suffix}")
    }
}
