/// Return the standard AUTO-GENERATED header comment for a generated source file.
#[must_use]
pub fn banner(schemas_version: &str) -> String {
    format!(
        "// AUTO-GENERATED by crabka-protocol-codegen against {schemas_version}. Do not edit.\n"
    )
}

/// Format an integer string as a Rust literal with underscores every 3 digits
/// from the right. This satisfies `clippy::unreadable_literal` for large
/// numbers, for example `-2_147_483_648i32`.
///
/// This function handles hex literals (`0x...`). It parses them to decimal
/// first, so the output is a clean decimal literal, for example
/// `"0x7fffffff"` → `2_147_483_647i32`.
#[must_use]
pub fn format_int_literal(s: &str, suffix: &str) -> String {
    // Normalise hex literals to decimal so we don't produce malformed output
    // like `0_x7f_fff_fffi32`.
    let (negative_in, s) = if let Some(rest) = s.strip_prefix('-') {
        (true, rest)
    } else {
        (false, s)
    };
    let s = s.trim();
    // Try to parse as hex; on failure fall through and treat as decimal string.
    let decimal_string: String;
    let (negative, digits): (bool, &str) =
        if let Some(hex) = s.strip_prefix("0x").or_else(|| s.strip_prefix("0X")) {
            // Parse the hex digits as u64 then reinterpret the bits at the target
            // type's width. A 32-bit constant like `0xffffffff` for an `i32` field
            // means -1, not 4_294_967_295 (which would overflow the literal).
            if let Ok(v) = u64::from_str_radix(hex, 16) {
                let signed = hex_to_signed(v, suffix);
                if negative_in || signed < 0 {
                    decimal_string = format!("{}", signed.unsigned_abs());
                    (true, &decimal_string)
                } else {
                    decimal_string = format!("{signed}");
                    (false, &decimal_string)
                }
            } else {
                // Fallback: keep the hex string as-is (should not happen with valid schemas).
                decimal_string = s.to_string();
                (negative_in, &decimal_string)
            }
        } else {
            decimal_string = s.to_string();
            (negative_in, &decimal_string)
        };
    let underscored: String = {
        let chars: Vec<char> = digits.chars().collect();
        let mut result = String::new();
        let len = chars.len();
        for (i, &c) in chars.iter().enumerate() {
            if i > 0 && (len - i).is_multiple_of(3) {
                result.push('_');
            }
            result.push(c);
        }
        result
    };
    if negative {
        format!("-{underscored}{suffix}")
    } else {
        format!("{underscored}{suffix}")
    }
}

/// Reinterpret the bits of a hex literal at the width of its Rust type suffix,
/// for example `"i32"` or `"i64"`. For a signed suffix the top bit of that
/// width sign-extends, so `0xffffffff` with `"i32"` yields `-1`. This function
/// returns unsigned suffixes and 64-bit widths unchanged.
fn hex_to_signed(v: u64, suffix: &str) -> i64 {
    let bits: u32 = suffix.trim_start_matches(['i', 'u']).parse().unwrap_or(64);
    if bits >= 64 {
        return v.cast_signed();
    }
    let mask = (1u64 << bits) - 1;
    let x = v & mask;
    if suffix.starts_with('i') && (x & (1u64 << (bits - 1))) != 0 {
        let shift = 64 - bits;
        (x << shift).cast_signed() >> shift
    } else {
        i64::try_from(x).expect("sub-64-bit unsigned literal must fit in i64")
    }
}

#[cfg(test)]
mod tests {
    use assert2::assert;

    use super::*;

    #[test]
    fn decimal_literals() {
        for (input, want) in [
            ("0", "0i32"),
            ("-1", "-1i32"),
            ("2147483647", "2_147_483_647i32"),
            ("-2147483648", "-2_147_483_648i32"),
        ] {
            assert!(format_int_literal(input, "i32") == want);
        }
    }

    #[test]
    fn hex_positive_normalizes_to_decimal() {
        assert!(format_int_literal("0x7fffffff", "i32") == "2_147_483_647i32");
        assert!(format_int_literal("0X10", "i32") == "16i32");
    }

    #[test]
    fn hex_high_bit_is_sign_extended_to_target_width() {
        // 0xffffffff as i32 is -1, not 4_294_967_295 (which would overflow i32).
        // The same 32-bit pattern widened to i64 is a large positive value.
        for (input, suffix, want) in [
            ("0xffffffff", "i32", "-1i32"),
            ("0x80000000", "i32", "-2_147_483_648i32"),
            ("0xffffffff", "i64", "4_294_967_295i64"),
        ] {
            assert!(format_int_literal(input, suffix) == want);
        }
        assert!(hex_to_signed(0x4000_0000_0000_0000, "i63") == -(1i64 << 62));
    }
}
