//! Emit a Rust source file that provides:
//!   - `CASES: &[Case]` -- a static table of `(message, api_key, version, kind)` cases
//!   - `default_json_for(name)` -- JSON the oracle should accept for default fixture
//!   - `encode_default(name, version)` -- Rust-encoded bytes via `Default::default()`
//!
//! Consumed by `crates/protocol/tests/differential_all.rs` via `include!`.

use proc_macro2::{Literal, TokenStream};
use quote::{format_ident, quote};

use crate::ir::{MessageSpec, MessageType};
use crate::name_conv;

/// Maximum version we will ever iterate to. Schemas with open-ended
/// `validVersions` (e.g. `0+`) would produce `i16::MAX` iterations, which is
/// wrong. In practice all active Kafka 4.2 schemas have bounded ranges, but
/// cap defensively to avoid catastrophic output.
const MAX_VERSION_CAP: i16 = 127;

#[must_use]
pub fn emit(specs: &[MessageSpec], schemas_version: &str) -> String {
    let tokens = emit_tokens(specs);
    let file = syn::parse2::<syn::File>(tokens).expect("differential table must be valid Rust");
    format!(
        "// AUTO-GENERATED by crabka-protocol-codegen against {schemas_version}. Do not edit.\n\n{}",
        prettyplease::unparse(&file)
    )
}

fn emit_tokens(specs: &[MessageSpec]) -> TokenStream {
    let cases = case_entries(specs);
    let encode_arms = encode_default_arms(specs);
    let default_json_arms = default_json_arms(specs);
    let roundtrip_arms = roundtrip_arms(specs);
    let request_header_arms = request_header_arms(specs);
    let response_header_arms = response_header_arms(specs);

    quote! {
        use bytes::BytesMut;
        #[allow(unused_imports)]
        use crabka_protocol::Encode;

        #[derive(Debug, Clone, Copy)]
        pub struct Case {
            pub name: &'static str,
            pub api_key: i16,
            pub version: i16,
            pub kind: Kind,
        }

        #[derive(Debug, Clone, Copy)]
        pub enum Kind {
            Request,
            Response,
            RequestHeader,
            ResponseHeader,
        }

        pub const CASES: &[Case] = &[#(#cases)*];

        #[must_use]
        #[allow(clippy::too_many_lines)]
        pub fn encode_default(name: &str, version: i16) -> Vec<u8> {
            match name {
                #(#encode_arms)*
                _ => panic!("unknown message in encode_default: {name}"),
            }
        }

        #[must_use]
        #[allow(clippy::too_many_lines)]
        pub fn default_json_for(name: &str, version: i16) -> ::serde_json::Value {
            match name {
                #(#default_json_arms)*
                _ => panic!("unknown message in default_json_for: {name}"),
            }
        }

        #[must_use]
        #[allow(clippy::too_many_lines)]
        pub fn roundtrip(name: &str, version: i16, bytes: &[u8]) -> Vec<u8> {
            use crabka_protocol::Decode;
            match name {
                #(#roundtrip_arms)*
                _ => panic!("unknown message in roundtrip: {name}"),
            }
        }

        #[must_use]
        #[allow(clippy::absurd_extreme_comparisons)]
        #[allow(clippy::match_same_arms)]
        #[allow(clippy::too_many_lines)]
        pub fn request_header_version(name: &str, version: i16) -> i16 {
            match name {
                "ControlledShutdownRequest" if version == 0 => 0,
                #(#request_header_arms)*
                _ => panic!("unknown request in request_header_version: {name}"),
            }
        }

        #[must_use]
        #[allow(clippy::absurd_extreme_comparisons)]
        #[allow(clippy::match_same_arms)]
        #[allow(clippy::too_many_lines)]
        pub fn response_header_version(name: &str, version: i16) -> i16 {
            match name {
                "ApiVersionsResponse" => 0,
                #(#response_header_arms)*
                _ => panic!("unknown response in response_header_version: {name}"),
            }
        }

        #[doc = " Decode and discard the request/response header from a full frame body,"]
        #[doc = " returning the remaining message bytes."]
        #[must_use]
        pub fn strip_frame_header(
            name: &str,
            version: i16,
            is_request: bool,
            frame: &[u8],
        ) -> Vec<u8> {
            use crabka_protocol::Decode;
            let mut cur = frame;
            if is_request {
                let hv = request_header_version(name, version);
                crabka_protocol::owned::request_header::RequestHeader::decode(&mut cur, hv)
                    .unwrap();
            } else {
                let hv = response_header_version(name, version);
                crabka_protocol::owned::response_header::ResponseHeader::decode(&mut cur, hv)
                    .unwrap();
            }
            cur.to_vec()
        }
    }
}

fn eligible_top_level(spec: &MessageSpec) -> bool {
    if spec.valid_versions.is_empty() || spec.internal {
        return false;
    }
    matches!(
        spec.message_type,
        MessageType::Request | MessageType::Response | MessageType::Header
    )
}

fn kind(spec: &MessageSpec) -> Option<TokenStream> {
    match spec.message_type {
        MessageType::Request => Some(quote!(Kind::Request)),
        MessageType::Response => Some(quote!(Kind::Response)),
        MessageType::Header => match spec.name.as_str() {
            "RequestHeader" => Some(quote!(Kind::RequestHeader)),
            "ResponseHeader" => Some(quote!(Kind::ResponseHeader)),
            _ => None,
        },
        MessageType::Data => None,
    }
}

fn case_entries(specs: &[MessageSpec]) -> Vec<TokenStream> {
    let mut entries = Vec::new();
    for spec in specs {
        let Some(kind) = kind(spec) else {
            continue;
        };
        if !eligible_top_level(spec) {
            continue;
        }
        let name = &spec.name;
        let api_key = Literal::i16_unsuffixed(spec.api_key.unwrap_or(0));
        let max = spec.valid_versions.max.min(MAX_VERSION_CAP);
        for version in spec.valid_versions.min..=max {
            let version = Literal::i16_unsuffixed(version);
            entries.push(quote! {
                Case {
                    name: #name,
                    api_key: #api_key,
                    version: #version,
                    kind: #kind,
                },
            });
        }
    }
    entries
}

fn encode_default_arms(specs: &[MessageSpec]) -> Vec<TokenStream> {
    specs
        .iter()
        .filter(|spec| eligible_top_level(spec))
        .map(|spec| {
            let name = &spec.name;
            let module = format_ident!("{}", name_conv::module_name(&spec.name));
            let ty = format_ident!("{}", name_conv::type_name(&spec.name));
            quote! {
                #name => {
                    let msg = crabka_protocol::owned::#module::#ty::default();
                    let mut buf = BytesMut::new();
                    msg.encode(&mut buf, version).unwrap();
                    buf.to_vec()
                }
            }
        })
        .collect()
}

fn default_json_arms(specs: &[MessageSpec]) -> Vec<TokenStream> {
    specs
        .iter()
        .filter(|spec| eligible_top_level(spec))
        .map(|spec| {
            let name = &spec.name;
            let module = format_ident!("{}", name_conv::module_name(&spec.name));
            quote!(#name => crabka_protocol::owned::#module::default_json(version),)
        })
        .collect()
}

fn roundtrip_arms(specs: &[MessageSpec]) -> Vec<TokenStream> {
    specs
        .iter()
        .filter(|spec| eligible_top_level(spec))
        .map(|spec| {
            let name = &spec.name;
            let module = format_ident!("{}", name_conv::module_name(&spec.name));
            let ty = format_ident!("{}", name_conv::type_name(&spec.name));
            quote! {
                #name => {
                    let mut cur = bytes;
                    let msg = crabka_protocol::owned::#module::#ty::decode(&mut cur, version)
                        .unwrap();
                    assert!(cur.is_empty());
                    let mut buf = BytesMut::new();
                    msg.encode(&mut buf, version).unwrap();
                    buf.to_vec()
                }
            }
        })
        .collect()
}

fn request_header_arms(specs: &[MessageSpec]) -> Vec<TokenStream> {
    specs
        .iter()
        .filter(|spec| eligible_top_level(spec))
        .filter(|spec| matches!(spec.message_type, MessageType::Request))
        .map(|spec| {
            let name = &spec.name;
            let flex_min = Literal::i16_unsuffixed(super::owned::flex_min(spec));
            quote!(#name => if version >= #flex_min { 2 } else { 1 },)
        })
        .collect()
}

fn response_header_arms(specs: &[MessageSpec]) -> Vec<TokenStream> {
    specs
        .iter()
        .filter(|spec| eligible_top_level(spec))
        .filter(|spec| matches!(spec.message_type, MessageType::Response))
        .filter(|spec| spec.name != "ApiVersionsResponse")
        .map(|spec| {
            let name = &spec.name;
            let flex_min = Literal::i16_unsuffixed(super::owned::flex_min(spec));
            quote!(#name => if version >= #flex_min { 1 } else { 0 },)
        })
        .collect()
}
