//! Emit a Rust source file that provides:
//!   - `CASES: &[Case]` — a static table of `(message, api_key, version, kind)` cases
//!   - `default_json_for(name)` — JSON the oracle should accept for default fixture
//!   - `encode_default(name, version)` — Rust-encoded bytes via `Default::default()`
//!
//! Consumed by `crates/protocol/tests/differential_all.rs` via `include!`.

use std::fmt::Write;

use crate::ir::{MessageSpec, MessageType};
use crate::name_conv;

/// Maximum version we will ever iterate to. Schemas with open-ended
/// `validVersions` (e.g. `0+`) would produce `i16::MAX` iterations, which is
/// wrong. In practice all active Kafka 4.2 schemas have bounded ranges, but
/// cap defensively to avoid catastrophic output.
const MAX_VERSION_CAP: i16 = 127;

#[must_use]
pub fn emit(specs: &[MessageSpec], schemas_version: &str) -> String {
    let mut out = String::new();
    writeln!(
        out,
        "// AUTO-GENERATED by crabka-protocol-codegen against {schemas_version}. Do not edit."
    )
    .unwrap();
    writeln!(out).unwrap();
    emit_preamble(&mut out);
    emit_cases_table(&mut out, specs);
    emit_encode_default(&mut out, specs);
    emit_default_json_for(&mut out, specs);
    out
}

fn emit_preamble(out: &mut String) {
    // Imports needed inside the include! context.
    writeln!(out, "use bytes::BytesMut;").unwrap();
    writeln!(out, "#[allow(unused_imports)]").unwrap();
    writeln!(out, "use crabka_protocol::Encode;").unwrap();
    writeln!(out).unwrap();

    // Case struct and Kind enum.
    writeln!(out, "#[derive(Debug, Clone, Copy)]").unwrap();
    writeln!(out, "pub struct Case {{").unwrap();
    writeln!(out, "    pub name: &'static str,").unwrap();
    writeln!(out, "    pub api_key: i16,").unwrap();
    writeln!(out, "    pub version: i16,").unwrap();
    writeln!(out, "    pub kind: Kind,").unwrap();
    writeln!(out, "}}").unwrap();
    writeln!(out).unwrap();
    writeln!(out, "#[derive(Debug, Clone, Copy)]").unwrap();
    writeln!(
        out,
        "pub enum Kind {{ Request, Response, RequestHeader, ResponseHeader }}"
    )
    .unwrap();
    writeln!(out).unwrap();
}

fn emit_cases_table(out: &mut String, specs: &[MessageSpec]) {
    writeln!(out, "pub const CASES: &[Case] = &[").unwrap();
    for s in specs {
        if s.valid_versions.is_empty() {
            continue;
        }
        let kind_str = match s.message_type {
            MessageType::Request => "Kind::Request",
            MessageType::Response => "Kind::Response",
            MessageType::Header => match s.name.as_str() {
                "RequestHeader" => "Kind::RequestHeader",
                "ResponseHeader" => "Kind::ResponseHeader",
                _ => continue, // Unknown header type — skip
            },
            MessageType::Data => continue, // Data-type schemas don't get top-level oracle cases
        };
        let api_key = s.api_key.unwrap_or(0);
        let max_v = s.valid_versions.max.min(MAX_VERSION_CAP);
        for v in s.valid_versions.min..=max_v {
            writeln!(
                out,
                "    Case {{ name: \"{}\", api_key: {api_key}, version: {v}, kind: {kind_str} }},",
                s.name
            )
            .unwrap();
        }
    }
    writeln!(out, "];").unwrap();
    writeln!(out).unwrap();
}

fn emit_encode_default(out: &mut String, specs: &[MessageSpec]) {
    writeln!(out, "#[must_use]").unwrap();
    writeln!(out, "#[allow(clippy::too_many_lines)]").unwrap();
    writeln!(
        out,
        "pub fn encode_default(name: &str, version: i16) -> Vec<u8> {{"
    )
    .unwrap();
    writeln!(out, "    match name {{").unwrap();
    for s in specs {
        if s.valid_versions.is_empty() {
            continue;
        }
        match s.message_type {
            MessageType::Request | MessageType::Response | MessageType::Header => {}
            MessageType::Data => continue,
        }
        let snake = name_conv::module_name(&s.name);
        let type_name = name_conv::type_name(&s.name);
        writeln!(out, "        \"{}\" => {{", s.name).unwrap();
        writeln!(
            out,
            "            let msg = crabka_protocol::owned::{snake}::{type_name}::default();"
        )
        .unwrap();
        writeln!(out, "            let mut buf = BytesMut::new();").unwrap();
        writeln!(out, "            msg.encode(&mut buf, version).unwrap();").unwrap();
        writeln!(out, "            buf.to_vec()").unwrap();
        writeln!(out, "        }}").unwrap();
    }
    writeln!(
        out,
        "        _ => panic!(\"unknown message in encode_default: {{name}}\"),"
    )
    .unwrap();
    writeln!(out, "    }}").unwrap();
    writeln!(out, "}}").unwrap();
    writeln!(out).unwrap();
}

/// Emit `default_json_for` dispatch.
///
/// `default_json(version)` is a module-level free function — call as
/// `module::default_json(version)`. The function only includes fields valid
/// for the requested version so the JVM converter doesn't reject unknown fields.
fn emit_default_json_for(out: &mut String, specs: &[MessageSpec]) {
    writeln!(out, "#[must_use]").unwrap();
    writeln!(out, "#[allow(clippy::too_many_lines)]").unwrap();
    writeln!(
        out,
        "pub fn default_json_for(name: &str, version: i16) -> ::serde_json::Value {{"
    )
    .unwrap();
    writeln!(out, "    match name {{").unwrap();
    for s in specs {
        if s.valid_versions.is_empty() {
            continue;
        }
        match s.message_type {
            MessageType::Request | MessageType::Response | MessageType::Header => {}
            MessageType::Data => continue,
        }
        let snake = name_conv::module_name(&s.name);
        writeln!(
            out,
            "        \"{}\" => crabka_protocol::owned::{snake}::default_json(version),",
            s.name
        )
        .unwrap();
    }
    writeln!(
        out,
        "        _ => panic!(\"unknown message in default_json_for: {{name}}\"),"
    )
    .unwrap();
    writeln!(out, "    }}").unwrap();
    writeln!(out, "}}").unwrap();
}
