//! Emit a Rust source file that provides:
//!   - `CASES: &[Case]` — a static table of `(message, api_key, version, kind)` cases
//!   - `default_json_for(name)` — JSON the oracle should accept for default fixture
//!   - `encode_default(name, version)` — Rust-encoded bytes from `Default::default()`
//!
//! `crates/protocol/tests/differential_all.rs` consumes the file with
//! `include!`.
//!
//! This module emits with `proc_macro2` and `quote!` instead of `writeln!`.
//! See `emit::api_key_enum_quote` for the overall pattern.

use proc_macro2::{Literal, TokenStream};
use quote::{format_ident, quote};

use crate::{
    ir::{MessageSpec, MessageType},
    name_conv,
};

/// Maximum version this emitter ever iterates to. Schemas with open-ended
/// `validVersions`, such as `0+`, would produce `i16::MAX` iterations, which is
/// wrong. In practice all active Kafka 4.2 schemas have bounded ranges, but
/// this cap is a defence against enormous output.
const MAX_VERSION_CAP: i16 = 127;

#[must_use]
/// # Panics
/// Panics if the validated schema model cannot be represented as the expected Rust syntax tree.
pub fn emit(specs: &[MessageSpec], schemas_version: &str) -> String {
    let banner = format!(
        "// AUTO-GENERATED by crabka-protocol-codegen against {schemas_version}. Do not edit.\n\n"
    );

    let tokens = build_body(specs);

    // Validate at generation time; rustfmt (applied by the caller) does the
    // actual formatting. See `crate::fmt`.
    let _validate: syn::File =
        syn::parse2(tokens.clone()).expect("generated differential_table must be valid Rust");

    format!("{banner}{tokens}")
}

fn build_body(specs: &[MessageSpec]) -> TokenStream {
    let mut ts = TokenStream::new();
    ts.extend(build_preamble());
    ts.extend(build_cases_table(specs));
    ts.extend(build_encode_default(specs));
    ts.extend(build_default_json_for(specs));
    ts.extend(build_roundtrip(specs));
    ts.extend(build_header_versions(specs));
    ts.extend(build_strip_frame_header());
    ts
}

fn build_preamble() -> TokenStream {
    quote! {
        use bytes::BytesMut;
        #[allow(unused_imports)]
        use crabka_protocol::Encode;

        #[derive(Debug, Clone, Copy)]
        pub struct Case {
            pub name: &'static str,
            pub api_key: i16,
            pub version: i16,
            pub kind: Kind,
        }

        #[derive(Debug, Clone, Copy)]
        pub enum Kind { Request, Response, RequestHeader, ResponseHeader }
    }
}

fn build_cases_table(specs: &[MessageSpec]) -> TokenStream {
    let rows: Vec<TokenStream> = specs
        .iter()
        .flat_map(|s| {
            if s.valid_versions.is_empty() || s.internal {
                return Vec::new();
            }
            let kind_tokens: TokenStream = match s.message_type {
                MessageType::Request => quote!(Kind::Request),
                MessageType::Response => quote!(Kind::Response),
                MessageType::Header => match s.name.as_str() {
                    "RequestHeader" => quote!(Kind::RequestHeader),
                    "ResponseHeader" => quote!(Kind::ResponseHeader),
                    _ => return Vec::new(), // Unknown header type — skip
                },
                MessageType::Data => return Vec::new(),
            };
            let api_key = Literal::i16_unsuffixed(s.api_key.unwrap_or(0));
            let name_lit = Literal::string(&s.name);
            let max_v = s.valid_versions.max.min(MAX_VERSION_CAP);
            (s.valid_versions.min..=max_v)
                .map(|v| {
                    let v_lit = Literal::i16_unsuffixed(v);
                    let kind = kind_tokens.clone();
                    quote! {
                        Case { name: #name_lit, api_key: #api_key, version: #v_lit, kind: #kind },
                    }
                })
                .collect()
        })
        .collect();

    quote! {
        pub const CASES: &[Case] = &[
            #(#rows)*
        ];
    }
}

fn build_encode_default(specs: &[MessageSpec]) -> TokenStream {
    let arms: Vec<TokenStream> = specs
        .iter()
        .filter_map(|s| {
            if s.valid_versions.is_empty() || s.internal {
                return None;
            }
            match s.message_type {
                MessageType::Request | MessageType::Response | MessageType::Header => {}
                MessageType::Data => return None,
            }
            let snake = name_conv::module_name(&s.name);
            let snake_ident = format_ident!("{snake}");
            let type_ident = format_ident!("{}", name_conv::type_name(&s.name));
            let name_lit = Literal::string(&s.name);
            Some(quote! {
                #name_lit => {
                    let msg = crabka_protocol::owned::#snake_ident::#type_ident::default();
                    let mut buf = BytesMut::new();
                    msg.encode(&mut buf, version).unwrap();
                    buf.to_vec()
                }
            })
        })
        .collect();
    let helpers: Vec<_> = arms
        .chunks(8)
        .enumerate()
        .map(|(index, chunk)| {
            let helper = format_ident!("encode_default_{index}");
            quote! {
                fn #helper(name: &str, version: i16) -> Option<Vec<u8>> {
                    Some(match name {
                        #(#chunk)*
                        _ => return None,
                    })
                }
            }
        })
        .collect();
    let calls = helpers.iter().enumerate().map(|(index, _)| {
        let helper = format_ident!("encode_default_{index}");
        quote!(result = result.or_else(|| #helper(name, version));)
    });

    quote! {
        #(#helpers)*
        /// # Panics
        ///
        /// Panics when `name` does not identify a generated protocol message.
        #[must_use]
        pub fn encode_default(name: &str, version: i16) -> Vec<u8> {
            let mut result = None;
            #(#calls)*
            result.unwrap_or_else(|| panic!("unknown message in encode_default: {name}"))
        }
    }
}

fn build_default_json_for(specs: &[MessageSpec]) -> TokenStream {
    let arms: Vec<TokenStream> = specs
        .iter()
        .filter_map(|s| {
            if s.valid_versions.is_empty() || s.internal {
                return None;
            }
            match s.message_type {
                MessageType::Request | MessageType::Response | MessageType::Header => {}
                MessageType::Data => return None,
            }
            let snake = name_conv::module_name(&s.name);
            let snake_ident = format_ident!("{snake}");
            let name_lit = Literal::string(&s.name);
            Some(quote! {
                #name_lit => crabka_protocol::owned::#snake_ident::default_json(version),
            })
        })
        .collect();
    let helpers: Vec<_> = arms
        .chunks(60)
        .enumerate()
        .map(|(index, chunk)| {
            let helper = format_ident!("default_json_for_{index}");
            quote! {
                fn #helper(name: &str, version: i16) -> Option<::serde_json::Value> {
                    Some(match name {
                        #(#chunk)*
                        _ => return None,
                    })
                }
            }
        })
        .collect();
    let calls = helpers.iter().enumerate().map(|(index, _)| {
        let helper = format_ident!("default_json_for_{index}");
        quote!(result = result.or_else(|| #helper(name, version));)
    });

    quote! {
        #(#helpers)*
        /// # Panics
        ///
        /// Panics when `name` does not identify a generated protocol message.
        #[must_use]
        pub fn default_json_for(name: &str, version: i16) -> ::serde_json::Value {
            let mut result = None;
            #(#calls)*
            result.unwrap_or_else(|| panic!("unknown message in default_json_for: {name}"))
        }
    }
}

fn build_roundtrip(specs: &[MessageSpec]) -> TokenStream {
    let arms: Vec<TokenStream> = specs
        .iter()
        .filter_map(|s| {
            if s.valid_versions.is_empty() || s.internal {
                return None;
            }
            match s.message_type {
                MessageType::Request | MessageType::Response | MessageType::Header => {}
                MessageType::Data => return None,
            }
            let snake = name_conv::module_name(&s.name);
            let snake_ident = format_ident!("{snake}");
            let type_ident = format_ident!("{}", name_conv::type_name(&s.name));
            let name_lit = Literal::string(&s.name);
            Some(quote! {
                #name_lit => {
                    let mut cur = bytes;
                    let msg = crabka_protocol::owned::#snake_ident::#type_ident::decode(&mut cur, version).unwrap();
                    assert!(cur.is_empty());
                    let mut buf = BytesMut::new();
                    msg.encode(&mut buf, version).unwrap();
                    buf.to_vec()
                }
            })
        })
        .collect();
    let helpers: Vec<_> = arms
        .chunks(6)
        .enumerate()
        .map(|(index, chunk)| {
            let helper = format_ident!("roundtrip_{index}");
            quote! {
                fn #helper(name: &str, version: i16, bytes: &[u8]) -> Option<Vec<u8>> {
                    use crabka_protocol::Decode;
                    Some(match name {
                        #(#chunk)*
                        _ => return None,
                    })
                }
            }
        })
        .collect();
    let calls = helpers.iter().enumerate().map(|(index, _)| {
        let helper = format_ident!("roundtrip_{index}");
        quote!(result = result.or_else(|| #helper(name, version, bytes));)
    });

    quote! {
        #(#helpers)*
        #[must_use]
        /// # Panics
        ///
        /// Panics when `name` does not identify a generated protocol message.
        pub fn roundtrip(name: &str, version: i16, bytes: &[u8]) -> Vec<u8> {
            let mut result = None;
            #(#calls)*
            result.unwrap_or_else(|| panic!("unknown message in roundtrip: {name}"))
        }
    }
}

fn build_header_versions(specs: &[MessageSpec]) -> TokenStream {
    let req_entries: Vec<TokenStream> = specs
        .iter()
        .filter_map(|s| {
            if s.valid_versions.is_empty() || s.internal {
                return None;
            }
            if !matches!(s.message_type, MessageType::Request) {
                return None;
            }
            let fm = super::owned::flex_min(s);
            let fm_lit = Literal::i16_unsuffixed(fm);
            let name_lit = Literal::string(&s.name);
            Some(quote! { (#name_lit, #fm_lit), })
        })
        .collect();

    let resp_entries: Vec<TokenStream> = specs
        .iter()
        .filter_map(|s| {
            if s.valid_versions.is_empty() || s.internal {
                return None;
            }
            if !matches!(s.message_type, MessageType::Response) {
                return None;
            }
            if s.name == "ApiVersionsResponse" {
                return None;
            }
            let fm = super::owned::flex_min(s);
            let fm_lit = Literal::i16_unsuffixed(fm);
            let name_lit = Literal::string(&s.name);
            Some(quote! { (#name_lit, #fm_lit), })
        })
        .collect();

    quote! {
        const REQUEST_FLEX_MIN: &[(&str, i16)] = &[#(#req_entries)*];
        const RESPONSE_FLEX_MIN: &[(&str, i16)] = &[#(#resp_entries)*];

        fn header_flex_min(table: &[(&str, i16)], name: &str, message_type: &str) -> i16 {
            table
                .iter()
                .find_map(|(candidate, minimum)| (*candidate == name).then_some(*minimum))
                .unwrap_or_else(|| panic!("unknown {message_type} in header version lookup: {name}"))
        }

        #[must_use]
        pub fn request_header_version(name: &str, version: i16) -> i16 {
            if name == "ControlledShutdownRequest" && version == 0 {
                return 0;
            }
            let minimum = header_flex_min(REQUEST_FLEX_MIN, name, "request");
            if minimum == i16::MIN || version >= minimum { 2 } else { 1 }
        }

        #[must_use]
        pub fn response_header_version(name: &str, version: i16) -> i16 {
            if name == "ApiVersionsResponse" {
                return 0;
            }
            let minimum = header_flex_min(RESPONSE_FLEX_MIN, name, "response");
            i16::from(minimum != i16::MIN && version >= minimum)
        }
    }
}

fn build_strip_frame_header() -> TokenStream {
    quote! {
        #[doc = " Decode and discard the request/response header from a full frame body,"]
        #[doc = " returning the remaining message bytes."]
        #[must_use]
        /// # Panics
        ///
        /// Panics when the frame header is malformed or `name` is unknown.
        pub fn strip_frame_header(name: &str, version: i16, is_request: bool, frame: &[u8]) -> Vec<u8> {
            use crabka_protocol::Decode;
            let mut cur = frame;
            if is_request {
                let hv = request_header_version(name, version);
                crabka_protocol::owned::request_header::RequestHeader::decode(&mut cur, hv).unwrap();
            } else {
                let hv = response_header_version(name, version);
                crabka_protocol::owned::response_header::ResponseHeader::decode(&mut cur, hv).unwrap();
            }
            cur.to_vec()
        }
    }
}
