//! A `quote!`-based reimplementation of the `owned` emitter.
//!
//! The structural scaffolding — struct definition, `Default`, the `Encode` /
//! `Decode` impls, tagged-field framing, nested structs and the `populated`
//! constructor — is built as a `proc_macro2::TokenStream` instead of being
//! concatenated with `write!`. `emit` returns the raw token text plus a banner;
//! the prettyplease pass in `crate::fmt`, run by the regeneration binary,
//! formats it.
//!
//! Wire correctness is covered by the generated-output snapshots plus the
//! protocol crate's round-trip and JVM-differential tests.
#![allow(clippy::doc_markdown, clippy::too_many_lines)]

use proc_macro2::{Literal, TokenStream};
use quote::{format_ident, quote};

use crate::emit::owned::{
    self, EmitError, base_type, field_forces_non_flex, flex_min, has_any_flex,
    has_float64_recursive, is_nullable, is_tagged, needs_manual_default, struct_path_for,
};
use crate::emit::quote_helpers as qh;
use crate::emit::{EmittedMessage, default_json, protocol_request};
use crate::ir::{FieldSpec, MessageSpec, MessageType};
use crate::name_conv;
use crate::resolve::{self, Resolution};

type ResMap = std::collections::HashMap<String, Resolution>;

/// `is_flexible(version)` for top-level messages, `version >= N` (the message's
/// flexible threshold) for nested structs whose version flows in from a parent.
enum FlexSource {
    TopLevel,
    Nested(i16),
}

impl FlexSource {
    fn tokens(&self) -> TokenStream {
        match self {
            FlexSource::TopLevel => quote!(is_flexible(version)),
            FlexSource::Nested(fm) => {
                let n = Literal::i16_unsuffixed(*fm);
                quote!(version >= #n)
            }
        }
    }
}

pub fn emit(spec: &MessageSpec, schemas_version: &str) -> Result<EmittedMessage, EmitError> {
    let res_map = resolve::resolve_message(spec)?;
    let lenient = matches!(spec.message_type, MessageType::Response);
    let commons = owned::emit_common_structs(spec, schemas_version, &res_map, lenient);

    // Top-level struct + impls + populated, then sibling structs for nested types.
    let version_err = version_err(spec);
    let mut structural = struct_block(
        &name_conv::type_name(&spec.name),
        &spec.fields,
        &res_map,
        &FlexSource::TopLevel,
        Some(version_err),
        has_any_flex(spec),
        lenient,
    );
    structural.extend(nested_structs(
        &spec.fields,
        flex_min(spec),
        &res_map,
        lenient,
    ));

    // Reuse the string blocks that are already correct: imports, constants, the
    // default_json oracle helper, and the ProtocolRequest impl.
    let mut imports = String::new();
    owned::emit_imports(&mut imports, spec);
    let mut constants = String::new();
    owned::emit_constants(&mut constants, spec);
    let banner = format!(
        "// AUTO-GENERATED by crabka-protocol-codegen against {schemas_version}. Do not edit.\n\n"
    );
    let dj = default_json::emit_default_json(spec);
    let pr = protocol_request::emit_protocol_request_tokens(spec);

    let primary = format!("{banner}{imports}{constants}\n{structural}\n{dj}\n");
    let primary = match pr {
        Some(pr) => format!("{primary}{pr}\n"),
        None => primary,
    };

    // Validate at generation time; prettyplease (the caller's secondary step)
    // also re-checks, but a syn error here is more precise.
    syn::parse_str::<syn::File>(&primary).map_err(|e| {
        EmitError::Unsupported(format!(
            "owned_quote produced invalid Rust for {}: {e}",
            spec.name
        ))
    })?;

    Ok(EmittedMessage { primary, commons })
}

fn version_err(spec: &MessageSpec) -> TokenStream {
    match spec.message_type {
        MessageType::Request | MessageType::Response => {
            quote!(return Err(ProtocolError::UnsupportedVersion { api_key: API_KEY, version });)
        }
        MessageType::Header | MessageType::Data => {
            let msg = format!("{} version out of range", spec.name);
            quote!(return Err(ProtocolError::SchemaMismatch(#msg));)
        }
    }
}

/// A struct definition, its `Default` (when non-trivial), the `Encode`/`Decode`
/// impls and the test `populated` constructor. Shared by the top-level message
/// type and every nested struct (they differ only in flex source and guard).
fn struct_block(
    name: &str,
    fields: &[FieldSpec],
    res_map: &ResMap,
    flex: &FlexSource,
    guard: Option<TokenStream>,
    has_flex: bool,
    lenient: bool,
) -> TokenStream {
    let ty = format_ident!("{name}");
    let eq = if has_float64_recursive(fields) {
        quote!()
    } else {
        quote!(, Eq)
    };
    let manual_default = needs_manual_default(fields);
    let default_derive = if manual_default {
        quote!()
    } else {
        quote!(, Default)
    };

    let field_defs = ordered(fields).map(|f| {
        let name = format_ident!("{}", name_conv::field_name(&f.name));
        let nullable = is_nullable(f) || (is_tagged(f) && default_is_null(f));
        let ty = qh::owned_type_tokens(
            &f.field_type,
            nullable,
            struct_path_for(f, res_map).as_deref(),
        );
        quote!(pub #name: #ty,)
    });

    let default_impl = manual_default.then(|| {
        let assigns = ordered(fields).map(|f| {
            let name = format_ident!("{}", name_conv::field_name(&f.name));
            let expr = qh::owned_default_tokens(f);
            quote!(#name: #expr,)
        });
        quote! {
            impl Default for #ty {
                fn default() -> Self {
                    Self {
                        #(#assigns)*
                        unknown_tagged_fields: Default::default(),
                    }
                }
            }
        }
    });

    let flex_src = flex.tokens();
    let guard = guard.map(|err| {
        quote! {
            if !(MIN_VERSION..=MAX_VERSION).contains(&version) { #err }
        }
    });

    let encode_body = encode_body(fields, res_map, has_flex);
    let len_body = len_body(fields, res_map, has_flex);
    let decode_body = decode_body(fields, res_map, has_flex, lenient);
    let populated = populated_impl(&ty, fields, res_map);

    quote! {
        #[derive(Debug, Clone, PartialEq #eq #default_derive)]
        pub struct #ty {
            #(#field_defs)*
            pub unknown_tagged_fields: UnknownTaggedFields,
        }

        #default_impl

        impl Encode for #ty {
            fn encode<B: BufMut>(&self, buf: &mut B, version: i16) -> Result<(), ProtocolError> {
                #guard
                let flex = #flex_src;
                #encode_body
                Ok(())
            }
            fn encoded_len(&self, version: i16) -> usize {
                let flex = #flex_src;
                let mut n: usize = 0;
                #len_body
                n
            }
        }

        impl<'de> Decode<'de> for #ty {
            fn decode<B: Buf>(buf: &mut B, version: i16) -> Result<Self, ProtocolError> {
                #guard
                let flex = #flex_src;
                let mut out = Self::default();
                #decode_body
                Ok(out)
            }
        }

        #populated
    }
}

/// Fields in emission order: non-tagged first, then tagged (matches the string
/// emitter so struct layout and round-trips are identical).
fn ordered(fields: &[FieldSpec]) -> impl Iterator<Item = &FieldSpec> {
    fields
        .iter()
        .filter(|f| !is_tagged(f))
        .chain(fields.iter().filter(|f| is_tagged(f)))
}

fn default_is_null(f: &FieldSpec) -> bool {
    matches!(&f.default, Some(serde_json::Value::Null))
}

// --- encode -----------------------------------------------------------------

fn encode_body(fields: &[FieldSpec], res_map: &ResMap, has_flex: bool) -> TokenStream {
    let stmts = fields
        .iter()
        .filter(|f| !is_tagged(f))
        .map(|f| encode_one(f, res_map));
    let trailer = has_flex.then(|| {
        let has_tagged = fields.iter().any(is_tagged);
        let mut_kw = if has_tagged { quote!(mut) } else { quote!() };
        let adds = fields
            .iter()
            .filter(|f| is_tagged(f))
            .map(|f| encode_tagged(f, res_map));
        quote! {
            if flex {
                let #mut_kw tagged = WriteTaggedFields::new();
                #(#adds)*
                tagged.write(buf, &self.unknown_tagged_fields);
            }
        }
    });
    quote!(#(#stmts)* #trailer)
}

fn encode_one(f: &FieldSpec, res_map: &ResMap) -> TokenStream {
    let field = format_ident!("{}", name_conv::field_name(&f.name));
    let cond = qh::version_cond_tokens(f.versions);
    let expr = quote!(self.#field);
    let buf = format_ident!("buf");
    let inner = if let Some(nc) = qh::nullable_split_cond_tokens(f) {
        let nb = qh::owned_encode_call(&f.field_type, expr.clone(), true, res_map, &buf);
        let nnb = qh::owned_encode_call_option_as_non_nullable(
            &f.field_type,
            expr.clone(),
            res_map,
            &buf,
        );
        non_flex_wrap(f, quote!(if #nc { #nb } else { #nnb }))
    } else {
        let b = qh::owned_encode_call(&f.field_type, expr, is_nullable(f), res_map, &buf);
        non_flex_wrap(f, b)
    };
    quote!(if #cond { #inner })
}

/// `flexibleVersions: "none"` on a field forces the legacy codec: shadow `flex`
/// to `false` for that field's body.
fn non_flex_wrap(f: &FieldSpec, body: TokenStream) -> TokenStream {
    if field_forces_non_flex(f) {
        quote!({ let flex = false; #body })
    } else {
        body
    }
}

fn encode_tagged(f: &FieldSpec, res_map: &ResMap) -> TokenStream {
    let field = format_ident!("{}", name_conv::field_name(&f.name));
    let tag = Literal::u32_unsuffixed(f.tag.expect("tagged field has tag"));
    let nullable = is_nullable(f) || default_is_null(f);
    let expr = quote!(self.#field);
    let b = format_ident!("b");
    let body = qh::owned_encode_call(&f.field_type, expr.clone(), nullable, res_map, &b);
    let len = qh::owned_encoded_len_expr(&f.field_type, expr, nullable, res_map);
    let is_default = qh::tagged_is_default_tokens(f, false);
    quote! {
        if !(#is_default) {
            let payload = encode_to_bytes(#len, |b| { #body; Ok(()) });
            tagged.add(#tag, payload);
        }
    }
}

// --- encoded_len ------------------------------------------------------------

fn len_body(fields: &[FieldSpec], res_map: &ResMap, has_flex: bool) -> TokenStream {
    let stmts = fields
        .iter()
        .filter(|f| !is_tagged(f))
        .map(|f| len_one(f, res_map));
    let trailer = has_flex.then(|| {
        let has_tagged = fields.iter().any(is_tagged);
        let mut_kw = if has_tagged { quote!(mut) } else { quote!() };
        let pushes = fields
            .iter()
            .filter(|f| is_tagged(f))
            .map(|f| len_tagged(f, res_map));
        quote! {
            if flex {
                let #mut_kw known_pairs: Vec<(u32, usize)> = Vec::new();
                #(#pushes)*
                n += tagged_fields_len(&known_pairs, &self.unknown_tagged_fields);
            }
        }
    });
    quote!(#(#stmts)* #trailer)
}

fn len_one(f: &FieldSpec, res_map: &ResMap) -> TokenStream {
    let field = format_ident!("{}", name_conv::field_name(&f.name));
    let cond = qh::version_cond_tokens(f.versions);
    let expr = quote!(self.#field);
    let inner = if let Some(nc) = qh::nullable_split_cond_tokens(f) {
        let nb = qh::owned_encoded_len_expr(&f.field_type, expr.clone(), true, res_map);
        let nnb =
            qh::owned_encoded_len_expr_option_as_non_nullable(&f.field_type, expr.clone(), res_map);
        non_flex_wrap(f, quote!(if #nc { #nb } else { #nnb }))
    } else {
        let b = qh::owned_encoded_len_expr(&f.field_type, expr, is_nullable(f), res_map);
        non_flex_wrap(f, b)
    };
    quote!(if #cond { n += #inner; })
}

fn len_tagged(f: &FieldSpec, res_map: &ResMap) -> TokenStream {
    let field = format_ident!("{}", name_conv::field_name(&f.name));
    let tag = Literal::u32_unsuffixed(f.tag.expect("tagged field has tag"));
    let nullable = is_nullable(f) || default_is_null(f);
    let len = qh::owned_encoded_len_expr(&f.field_type, quote!(self.#field), nullable, res_map);
    let is_default = qh::tagged_is_default_tokens(f, false);
    quote! {
        if !(#is_default) {
            known_pairs.push((#tag, #len));
        }
    }
}

// --- decode -----------------------------------------------------------------

fn decode_body(
    fields: &[FieldSpec],
    res_map: &ResMap,
    has_flex: bool,
    lenient: bool,
) -> TokenStream {
    let stmts = fields
        .iter()
        .filter(|f| !is_tagged(f))
        .map(|f| decode_one(f, res_map, lenient));
    let trailer = has_flex.then(|| decode_tagged_block(fields, res_map, lenient));
    quote!(#(#stmts)* #trailer)
}

fn decode_one(f: &FieldSpec, res_map: &ResMap, lenient: bool) -> TokenStream {
    let field = format_ident!("{}", name_conv::field_name(&f.name));
    let cond = qh::version_cond_tokens(f.versions);
    let buf = format_ident!("buf");
    let inner = if let Some(nc) = qh::nullable_split_cond_tokens(f) {
        let nb = qh::owned_decode_call(&f.field_type, true, res_map, &buf, lenient);
        let nnb_call = qh::owned_decode_call(&f.field_type, false, res_map, &buf, lenient);
        let nnb = qh::wrap_non_nullable_for_option_tokens(nnb_call);
        non_flex_wrap(f, quote!(if #nc { #nb } else { #nnb }))
    } else {
        let b = qh::owned_decode_call(&f.field_type, is_nullable(f), res_map, &buf, lenient);
        non_flex_wrap(f, b)
    };
    quote!(if #cond { out.#field = #inner; })
}

fn decode_tagged_block(fields: &[FieldSpec], res_map: &ResMap, lenient: bool) -> TokenStream {
    let has_tagged = fields.iter().any(is_tagged);
    if !has_tagged {
        return quote! {
            if flex {
                out.unknown_tagged_fields = read_tagged_fields(buf, |_tag, _payload| { Ok(false) })?;
            }
        };
    }
    let slots = fields.iter().filter(|f| is_tagged(f)).map(|f| {
        let slot = format_ident!("tag_{}", name_conv::field_name(&f.name));
        quote!(let mut #slot = None;)
    });
    let arms = fields.iter().filter(|f| is_tagged(f)).map(|f| {
        let slot = format_ident!("tag_{}", name_conv::field_name(&f.name));
        let tag = Literal::u32_unsuffixed(f.tag.expect("tagged field has tag"));
        let nullable = is_nullable(f) || default_is_null(f);
        let b = format_ident!("b");
        let call = qh::owned_decode_call(&f.field_type, nullable, res_map, &b, lenient);
        quote!(#tag => { #slot = Some({ let b: &mut &[u8] = payload; #call }); Ok(true) })
    });
    let writebacks = fields.iter().filter(|f| is_tagged(f)).map(|f| {
        let field = format_ident!("{}", name_conv::field_name(&f.name));
        let slot = format_ident!("tag_{}", name_conv::field_name(&f.name));
        quote!(if let Some(v) = #slot { out.#field = v; })
    });
    quote! {
        if flex {
            #(#slots)*
            out.unknown_tagged_fields = read_tagged_fields(buf, |tag, payload| {
                match tag {
                    #(#arms)*
                    _ => Ok(false),
                }
            })?;
            #(#writebacks)*
        }
    }
}

// --- populated + nested -----------------------------------------------------

fn populated_impl(ty: &proc_macro2::Ident, fields: &[FieldSpec], res_map: &ResMap) -> TokenStream {
    let assigns = ordered(fields)
        .filter(|f| base_type(&f.field_type) != "records")
        .map(|f| {
            let field = format_ident!("{}", name_conv::field_name(&f.name));
            let option = is_nullable(f) || (is_tagged(f) && default_is_null(f));
            let value = qh::owned_populated_value_tokens(f, res_map, option);
            let cond = qh::version_cond_tokens(f.versions);
            quote!(if #cond { m.#field = #value; })
        });
    quote! {
        #[cfg(test)]
        impl #ty {
            #[must_use]
            pub fn populated(version: i16) -> Self {
                let mut m = Self::default();
                #(#assigns)*
                m
            }
        }
    }
}

/// Sibling struct definitions for every field that has its own `fields:` list,
/// depth-first. `flex_min_val` is the message's flexible threshold, which all
/// nested structs inherit.
fn nested_structs(
    fields: &[FieldSpec],
    flex_min_val: i16,
    res_map: &ResMap,
    lenient: bool,
) -> TokenStream {
    let mut out = TokenStream::new();
    for f in fields.iter().filter(|f| !f.fields.is_empty()) {
        let name = base_type(&f.field_type);
        out.extend(struct_block(
            name,
            &f.fields,
            res_map,
            &FlexSource::Nested(flex_min_val),
            None,
            flex_min_val < i16::MAX,
            lenient,
        ));
        out.extend(nested_structs(&f.fields, flex_min_val, res_map, lenient));
    }
    out
}
