use std::fmt::Write;

use crate::ir::{FlexibleVersions, MessageSpec};

/// Emit Rust source code for the owned flavor of `spec`. Only handles messages
/// whose fields use the primitives implemented in this slice: string/compact_string
/// and a small set of fixed-width types. Extension comes in later tasks.
pub fn emit(spec: &MessageSpec) -> Result<String, EmitError> {
    if spec.name != "ApiVersionsRequest" {
        return Err(EmitError::Unsupported(format!(
            "owned emitter does not yet support {}",
            spec.name
        )));
    }

    let api_key = spec.api_key.expect("validated earlier");
    let (flex_min, _) = match spec.flexible_versions {
        FlexibleVersions::Range(r) => (r.min, r.max),
        FlexibleVersions::None => (i16::MAX, i16::MAX),
    };
    let min_version = spec.valid_versions.min;
    let max_version = spec.valid_versions.max;

    let mut out = String::new();
    writeln!(out, "// AUTO-GENERATED by crabka-protocol-codegen. Do not edit.").unwrap();
    writeln!(out).unwrap();
    out.push_str(STATIC_HEADER);
    writeln!(out, "pub const API_KEY: i16 = {api_key};").unwrap();
    writeln!(out, "pub const MIN_VERSION: i16 = {min_version};").unwrap();
    writeln!(out, "pub const MAX_VERSION: i16 = {max_version};").unwrap();
    writeln!(out, "pub const FLEXIBLE_MIN: i16 = {flex_min};").unwrap();
    out.push_str(STATIC_BODY);
    Ok(out)
}

#[derive(Debug, thiserror::Error)]
pub enum EmitError {
    #[error("unsupported: {0}")]
    Unsupported(String),
}

const STATIC_HEADER: &str = r#"
use bytes::{Buf, BufMut};

use crate::primitives::string_bytes::{
    compact_string_len, get_compact_string_owned, put_compact_string,
};
use crate::tagged_fields::{read_tagged_fields, tagged_fields_len, WriteTaggedFields};
use crate::{Decode, Encode, ProtocolError, UnknownTaggedFields};

#[derive(Debug, Clone, PartialEq, Eq, Default)]
pub struct ApiVersionsRequest {
    pub client_software_name: String,
    pub client_software_version: String,
    pub unknown_tagged_fields: UnknownTaggedFields,
}

"#;

const STATIC_BODY: &str = r#"
fn is_flexible(version: i16) -> bool { version >= FLEXIBLE_MIN }

impl Encode for ApiVersionsRequest {
    fn encode<B: BufMut>(&self, buf: &mut B, version: i16) -> Result<(), ProtocolError> {
        if !(MIN_VERSION..=MAX_VERSION).contains(&version) {
            return Err(ProtocolError::UnsupportedVersion { api_key: API_KEY, version });
        }
        if version >= 3 {
            put_compact_string(buf, &self.client_software_name);
            put_compact_string(buf, &self.client_software_version);
            WriteTaggedFields::new().write(buf, &self.unknown_tagged_fields);
        }
        Ok(())
    }

    fn encoded_len(&self, version: i16) -> usize {
        if !is_flexible(version) { return 0; }
        let known: &[(u32, usize)] = &[];
        compact_string_len(&self.client_software_name)
            + compact_string_len(&self.client_software_version)
            + tagged_fields_len(known, &self.unknown_tagged_fields)
    }
}

impl<'de> Decode<'de> for ApiVersionsRequest {
    fn decode<B: Buf>(buf: &mut B, version: i16) -> Result<Self, ProtocolError> {
        if !(MIN_VERSION..=MAX_VERSION).contains(&version) {
            return Err(ProtocolError::UnsupportedVersion { api_key: API_KEY, version });
        }
        if !is_flexible(version) {
            return Ok(Self::default());
        }
        let client_software_name = get_compact_string_owned(buf)?;
        let client_software_version = get_compact_string_owned(buf)?;
        let unknown = read_tagged_fields(buf, |_tag, _payload| Ok(false))?;
        Ok(Self {
            client_software_name,
            client_software_version,
            unknown_tagged_fields: unknown,
        })
    }
}
"#;
