[package]
name = "crabka-log"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
rust-version = "1.95.0"
description = "Byte-compatible reader/writer for Apache Kafka's on-disk log format"

[lints]
workspace = true

[features]
default = []

[dependencies]
crabka-protocol = { version = "0.1", path = "../protocol", default-features = false }
bytes = { workspace = true }
thiserror = { workspace = true }
memmap2 = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
proptest = { workspace = true }
tempfile = { workspace = true }
hex = { workspace = true }
testcontainers = { workspace = true }
testcontainers-modules = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
