[package]
name = "crabka-docgen"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
rust-version.workspace = true
description = "Documentation generator for Crabka protocol, broker, and Kubernetes API artifacts"
publish = false

[lints]
workspace = true

[[bin]]
name = "crabka-docgen"
path = "src/main.rs"

[dependencies]
assert2 = { workspace = true }
crabka-operator = { version = "0.4.0", path = "../operator" }
crabka-broker = { version = "0.4.0", path = "../broker" }
crabka-protocol = { version = "0.4.1", path = "../protocol" }
crabka-raft = { version = "0.4.0", path = "../raft", features = ["scenarios"] }
anyhow = "1"
clap = { version = "4", features = ["derive"] }
serde_json = { workspace = true }
schemars = { workspace = true }
kube = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
