[package]
name = "crabka-broker-test-helpers"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
rust-version.workspace = true
publish = false

[lints]
workspace = true

[dependencies]
crabka-broker = { version = "0.3.8", path = "..", features = ["test-helpers"] }
