// Vendored minimal Prometheus remote_write v2 surface, pinned to 2.0-rc.4 shape.
// Source shape: prometheus/prometheus prompb/io/prometheus/write/v2/types.proto subset.
// License: Apache-2.0.
syntax = "proto3";

package io.prometheus.write.v2;

message Request {
  reserved 1 to 3;
  repeated string symbols = 4;
  repeated TimeSeries timeseries = 5;
}

message TimeSeries {
  repeated uint32 labels_refs = 1;
  repeated Sample samples = 2;
  repeated Histogram histograms = 3;
  repeated Exemplar exemplars = 4;
  Metadata metadata = 5;
  reserved 6;
}

message Sample {
  double value = 1;
  int64 timestamp = 2;
  int64 start_timestamp = 3;
}

message Exemplar {
  repeated uint32 labels_refs = 1;
  double value = 2;
  int64 timestamp = 3;
}

message Metadata {
  enum MetricType {
    METRIC_TYPE_UNSPECIFIED = 0;
    COUNTER = 1;
    GAUGE = 2;
    HISTOGRAM = 3;
    GAUGEHISTOGRAM = 4;
    SUMMARY = 5;
    INFO = 6;
    STATESET = 7;
  }
  MetricType type = 1;
  uint32 help_ref = 3;
  uint32 unit_ref = 4;
}

message Histogram {
  oneof count {
    uint64 count_int = 1;
    double count_float = 2;
  }
  double sum = 3;
  sint32 schema = 4;
  double zero_threshold = 5;
  oneof zero_count {
    uint64 zero_count_int = 6;
    double zero_count_float = 7;
  }
  repeated BucketSpan negative_spans = 8;
  repeated sint64 negative_deltas = 9;
  repeated double negative_counts = 10;
  repeated BucketSpan positive_spans = 11;
  repeated sint64 positive_deltas = 12;
  repeated double positive_counts = 13;
  enum ResetHint {
    RESET_HINT_UNSPECIFIED = 0;
    RESET_HINT_YES = 1;
    RESET_HINT_NO = 2;
    RESET_HINT_GAUGE = 3;
  }
  ResetHint reset_hint = 14;
  int64 timestamp = 15;
  repeated double custom_values = 16;
  int64 start_timestamp = 17;
}

message BucketSpan {
  sint32 offset = 1;
  uint32 length = 2;
}
