[package]
name = "crabka-cli"
publish = false
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
rust-version.workspace = true
description = "Operator CLI for Crabka (binary: `crabka`)"
repository = "https://github.com/robot-head/crabka"
homepage = "https://github.com/robot-head/crabka"
documentation = "https://docs.rs/crabka-cli"
readme = "README.md"
keywords = ["kafka", "cli", "operator", "crabka"]
categories = ["command-line-utilities"]

[[bin]]
name = "crabka"
path = "src/main.rs"

[lints]
workspace = true

[dependencies]
assert2 = { workspace = true }
clap = { workspace = true, features = ["env"] }
crabka-security = { workspace = true }
crabka-client-core = { version = "0.4.1", path = "../client-core" }
crabka-client-admin = { version = "0.4.1", path = "../client-admin" }
crabka-gres-balancer = { version = "0.4.0", path = "../gres-balancer" }
crabka-gres-control = { version = "0.4.0", path = "../gres-control" }
crabka-units = { workspace = true }
crabka-metadata = { version = "0.4.1", path = "../metadata" }
crabka-raft = { version = "0.4.0", path = "../raft" }
derive_more = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["rt-multi-thread", "macros", "fs"] }
serde-wincode = { workspace = true }
wincode = { workspace = true }
ring = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
uuid = { workspace = true }

[dev-dependencies]
crabka-broker = { version = "0.4.0", path = "../broker" }
tempfile = { workspace = true }
