// AUTO-GENERATED by crabka-protocol-codegen against a9ce3221537b8653448750697915607dc7936cf3. Do not edit.
include!(concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/generated/common/owned/streams_group_heartbeat_request/key_value.owned.rs"
));
