// AUTO-GENERATED by crabka-protocol-codegen against b25e89b6f842f11e4eb747e131a71153d9270536. Do not edit.
#![doc = " Borrowed-flavor generated message types."]
pub mod fetch_request;
pub mod fetch_response;
pub mod produce_request;
pub mod produce_response;
