[package]
name = "crabka-integration-tests"
version = "0.3.4"
edition = "2024"
license.workspace = true
publish = false

[dependencies]

[dev-dependencies]
assert2 = { workspace = true }
bon = { workspace = true }
bytes = { workspace = true }
crabka-broker = { path = "../broker", version = "0.3.4", features = ["test-helpers"] }
crabka-client-admin = { path = "../client-admin", version = "0.3.4" }
crabka-client-consumer = { path = "../client-consumer", version = "0.3.4" }
crabka-client-producer = { path = "../client-producer", version = "0.3.4" }
crabka-client-core = { path = "../client-core", version = "0.3.4" }
crabka-protocol = { path = "../protocol", version = "0.3.4", default-features = false }
crabka-security = { path = "../security", version = "0.3.4" }
crabka-log = { path = "../log", version = "0.3.4" }
tempfile = { workspace = true }
tokio = { workspace = true, features = ["rt", "rt-multi-thread", "sync", "time", "macros", "test-util"] }
tracing = { workspace = true }
tracing-subscriber = { workspace = true, features = ["env-filter"] }
tokio-util = { workspace = true, features = ["rt"] }
futures-util = { workspace = true }
proptest = { workspace = true }
uuid = { workspace = true }
