load("//:bazel/rust_package.bzl", "rust_package")

rust_package(
    name = "grpc-gateway",
    build_script = True,
    cargo_name = "crabka-grpc-gateway",
    crate_name = "crabka_grpc_gateway",
    lib_test_size = "small",
    protoc = True,
    test_size = "small",
    test_sizes = {
        "jvm_differential": "small",
    },
    test_tags = {
        "jvm_differential": ["manual"],
    },
)
