[package]
name = "crabka-metadata"
publish = false
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
rust-version.workspace = true
description = "Versioned metadata record types + immutable image for Crabka"
repository = "https://github.com/robot-head/crabka"
homepage = "https://github.com/robot-head/crabka"
documentation = "https://docs.rs/crabka-metadata"
readme = "README.md"
keywords = ["kafka", "metadata", "kraft", "crabka"]
categories = ["data-structures", "encoding"]

[lints]
workspace = true

[dependencies]
wincode = { workspace = true }
serde-wincode = { workspace = true }
bytes = { workspace = true }
serde = { workspace = true, features = ["derive"] }
crabka-protocol = { version = "0.3.8", path = "../protocol", default-features = false }
crabka-voters = { version = "0.3.8", path = "../voters" }
crabka-ids = { version = "0.3.8", path = "../ids" }
thiserror = { workspace = true }
uuid = { workspace = true }
crabka-security = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
assert2 = { workspace = true }
mutants = { workspace = true }
proptest = { workspace = true }
criterion = { version = "5.0.0", package = "codspeed-criterion-compat" }

[[bench]]
name = "image"
harness = false
