// AUTO-GENERATED by crabka-protocol-codegen against a9ce3221537b8653448750697915607dc7936cf3. Do not edit.
pub mod add_partitions_to_txn_partition_result;
pub mod add_partitions_to_txn_topic_result;
