load("//:bazel/rust_package.bzl", "rust_package")

filegroup(
    name = "conformance_data",
    srcs = glob(["tests/testdata/**"]),
    visibility = ["//crates/traces:__pkg__"],
)

rust_package(
    name = "traceql",
    cargo_name = "crabka-traceql",
    crate_name = "crabka_traceql",
    harnessless = ["golden_corpus"],
)
