load("//:bazel/rust_package.bzl", "rust_feature_binary", "rust_package")

rust_package(
    name = "profiles",
    build_script = True,
    cargo_name = "crabka-profiles",
    crate_name = "crabka_profiles",
    protoc = True,
)

rust_feature_binary(
    name = "crabka-profiles-heap__bin",
    crate_label = ":profiles",
    crate_root = "src/bin/crabka-profiles.rs",
    features = ["heap-profiling"],
    deps = ["@crates//:tikv-jemallocator"],
)
