// AUTO-GENERATED by crabka-protocol-codegen against a9ce3221537b8653448750697915607dc7936cf3. Do not edit.
// Clippy lints that fire on generated code patterns are suppressed here so
// that regenerating the file does not require manual allow annotations.
#![allow(
    clippy::absurd_extreme_comparisons,
    clippy::cast_possible_truncation,
    clippy::cast_possible_wrap,
    clippy::cast_sign_loss,
    clippy::default_trait_access,
    clippy::must_use_candidate,
    clippy::new_without_default,
    clippy::nonminimal_bool,
    clippy::too_many_lines,
    clippy::unnecessary_wraps,
    clippy::unreadable_literal,
    unused_mut,
    unused_variables
)]

include!(concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/generated/AddPartitionsToTxnResponse.owned.rs"
));
#[cfg(test)]
mod tests {
    use bytes::BytesMut;

    use super::*;
    use crate::{Decode, Encode};
    fn roundtrip(case: &str, msg: &AddPartitionsToTxnResponse, v: i16) {
        let mut buf = BytesMut::new();
        msg.encode(&mut buf, v).unwrap();
        assert2::assert!(msg.encoded_len(v) == buf.len(), "case {case}, version {v}");
        let bytes = buf.freeze();
        let mut cur = &bytes[..];
        let decoded = AddPartitionsToTxnResponse::decode(&mut cur, v).unwrap();
        assert2::assert!(cur.is_empty(), "case {case}, version {v}");
        let mut reencoded = BytesMut::new();
        decoded.encode(&mut reencoded, v).unwrap();
        assert2::assert!(&reencoded[..] == &bytes[..]);
        let _ = default_json(v);
    }
    #[test]
    fn roundtrip_cases_all_versions() {
        for v in MIN_VERSION..=MAX_VERSION {
            for (case, msg) in [
                ("default", AddPartitionsToTxnResponse::default()),
                ("populated", AddPartitionsToTxnResponse::populated(v)),
            ] {
                roundtrip(case, &msg, v);
            }
        }
    }
}
