// AUTO-GENERATED by crabka-protocol-codegen against a9ce3221537b8653448750697915607dc7936cf3. Do not edit.
include!(concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/generated/AlterPartitionReassignmentsResponse.owned.rs"
));
#[cfg(test)]
mod tests {
    use assert2::assert;
    use bytes::BytesMut;

    use super::*;
    use crate::{Decode, Encode};
    fn roundtrip(msg: &AlterPartitionReassignmentsResponse, v: i16) {
        let mut buf = BytesMut::new();
        msg.encode(&mut buf, v).unwrap();
        assert!(msg.encoded_len(v) == buf.len());
        let bytes = buf.freeze();
        let mut cur = &bytes[..];
        let decoded = AlterPartitionReassignmentsResponse::decode(&mut cur, v).unwrap();
        assert!(cur.is_empty());
        let mut reencoded = BytesMut::new();
        decoded.encode(&mut reencoded, v).unwrap();
        assert!(&reencoded[..] == &bytes[..]);
        let _ = default_json(v);
    }
    #[test]
    fn default_roundtrips_all_versions() {
        for v in MIN_VERSION..=MAX_VERSION {
            roundtrip(&AlterPartitionReassignmentsResponse::default(), v);
        }
    }
    #[test]
    fn populated_roundtrips_all_versions() {
        for v in MIN_VERSION..=MAX_VERSION {
            roundtrip(&AlterPartitionReassignmentsResponse::populated(v), v);
        }
    }
}
