// AUTO-GENERATED by crabka-protocol-codegen against a9ce3221537b8653448750697915607dc7936cf3. Do not edit.
// Clippy lints that fire on generated code patterns are suppressed here so
// that regenerating the file does not require manual allow annotations.
#![allow(
    clippy::absurd_extreme_comparisons,
    clippy::double_comparisons,
    clippy::elidable_lifetime_names,
    clippy::manual_string_new,
    clippy::must_use_candidate,
    clippy::unnecessary_wraps,
    clippy::cast_sign_loss,
    clippy::cast_possible_truncation,
    clippy::cast_possible_wrap,
    clippy::default_trait_access,
    clippy::derivable_impls,
    clippy::collapsible_if,
    clippy::too_many_lines,
    clippy::field_reassign_with_default,
    unused_mut,
    clippy::new_without_default,
    clippy::unreadable_literal,
    clippy::redundant_closure_for_method_calls,
    clippy::nonminimal_bool,
    clippy::bool_comparison,
    clippy::map_unwrap_or,
    clippy::option_as_ref_deref,
    clippy::manual_range_contains,
    clippy::borrow_deref_ref,
    clippy::explicit_auto_deref,
    clippy::unnecessary_semicolon,
    unused_imports,
    unused_variables
)]

include!(concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/generated/DefaultPrincipalData.owned.rs"
));

#[cfg(test)]
mod tests {
    use super::*;
    use crate::{Decode, Encode};
    use bytes::BytesMut;

    fn roundtrip(msg: &DefaultPrincipalData, v: i16) {
        let mut buf = BytesMut::new();
        msg.encode(&mut buf, v).unwrap();
        assert_eq!(msg.encoded_len(v), buf.len());
        let bytes = buf.freeze();
        let mut cur = &bytes[..];
        let decoded = DefaultPrincipalData::decode(&mut cur, v).unwrap();
        assert!(cur.is_empty());
        let mut reencoded = BytesMut::new();
        decoded.encode(&mut reencoded, v).unwrap();
        assert_eq!(&reencoded[..], &bytes[..]);
        // Exercise the JVM-oracle default-JSON builder for this version.
        let _ = default_json(v);
    }

    #[test]
    fn default_roundtrips_all_versions() {
        for v in MIN_VERSION..=MAX_VERSION {
            roundtrip(&DefaultPrincipalData::default(), v);
        }
    }

    #[test]
    fn populated_roundtrips_all_versions() {
        for v in MIN_VERSION..=MAX_VERSION {
            roundtrip(&DefaultPrincipalData::populated(v), v);
        }
    }
}
