// AUTO-GENERATED by crabka-protocol-codegen against a9ce3221537b8653448750697915607dc7936cf3. Do not edit.
// Clippy lints that fire on generated code patterns are suppressed here so
// that regenerating the file does not require manual allow annotations.
#![allow(
    clippy::absurd_extreme_comparisons,
    clippy::double_comparisons,
    clippy::elidable_lifetime_names,
    clippy::manual_string_new,
    clippy::must_use_candidate,
    clippy::unnecessary_wraps,
    clippy::cast_sign_loss,
    clippy::cast_possible_truncation,
    clippy::cast_possible_wrap,
    clippy::default_trait_access,
    clippy::derivable_impls,
    clippy::collapsible_if,
    clippy::new_without_default,
    clippy::unreadable_literal,
    clippy::redundant_closure_for_method_calls,
    clippy::nonminimal_bool,
    clippy::bool_comparison,
    clippy::map_unwrap_or,
    clippy::option_as_ref_deref,
    clippy::manual_range_contains,
    clippy::borrow_deref_ref,
    clippy::explicit_auto_deref,
    clippy::unnecessary_semicolon,
    unused_imports,
    unused_variables
)]

include!(concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/generated/DescribeProducersRequest.owned.rs"
));

#[cfg(test)]
mod tests {
    use super::*;
    use crate::{Decode, Encode};
    use bytes::BytesMut;

    #[test]
    fn min_version_roundtrips() {
        let v = MIN_VERSION;
        let msg = DescribeProducersRequest::default();
        let mut buf = BytesMut::new();
        msg.encode(&mut buf, v).unwrap();
        assert_eq!(msg.encoded_len(v), buf.len());
        let mut cur = &buf[..];
        let _decoded = DescribeProducersRequest::decode(&mut cur, v).unwrap();
        assert!(cur.is_empty(), "decoder left trailing bytes");
    }

    #[test]
    fn max_version_roundtrips() {
        let v = MAX_VERSION;
        let msg = DescribeProducersRequest::default();
        let mut buf = BytesMut::new();
        msg.encode(&mut buf, v).unwrap();
        assert_eq!(msg.encoded_len(v), buf.len());
        let mut cur = &buf[..];
        let decoded = DescribeProducersRequest::decode(&mut cur, v).unwrap();
        assert_eq!(decoded, msg);
        assert!(cur.is_empty(), "decoder left trailing bytes");
    }
}
