// AUTO-GENERATED by crabka-protocol-codegen against a9ce3221537b8653448750697915607dc7936cf3. Do not edit.
// Clippy lints that fire on generated code patterns are suppressed here so
// that regenerating the file does not require manual allow annotations.
#![allow(
    clippy::absurd_extreme_comparisons,
    clippy::cast_possible_truncation,
    clippy::cast_possible_wrap,
    clippy::cast_sign_loss,
    clippy::default_trait_access,
    clippy::must_use_candidate,
    clippy::new_without_default,
    clippy::nonminimal_bool,
    clippy::too_many_lines,
    clippy::unnecessary_wraps,
    clippy::unreadable_literal,
    unused_mut,
    unused_variables
)]

include!(concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/generated/EndTxnRequest.owned.rs"
));
#[cfg(test)]
mod tests {
    use assert2::assert;
    use bytes::BytesMut;

    use super::*;
    use crate::{Decode, Encode};
    fn roundtrip(case_name: &str, msg: &EndTxnRequest, v: i16) {
        let mut buf = BytesMut::new();
        msg.encode(&mut buf, v).unwrap();
        assert!(
            msg.encoded_len(v) == buf.len(),
            "{case_name} encoded length differs at version {v}"
        );
        let bytes = buf.freeze();
        let mut cur = &bytes[..];
        let decoded = EndTxnRequest::decode(&mut cur, v).unwrap();
        assert!(
            cur.is_empty(),
            "{case_name} left trailing bytes at version {v}"
        );
        let mut reencoded = BytesMut::new();
        decoded.encode(&mut reencoded, v).unwrap();
        assert!(
            &reencoded[..] == &bytes[..],
            "{case_name} re-encoding differs at version {v}"
        );
        let _ = default_json(v);
    }
    #[test]
    fn roundtrips_all_versions() {
        type TestCase1<'a> = (&'a str, fn(i16) -> EndTxnRequest);
        let cases: [TestCase1<'_>; 2] = [
            ("default", |_| EndTxnRequest::default()),
            ("populated", EndTxnRequest::populated),
        ];

        for (name, make_message) in cases {
            for v in MIN_VERSION..=MAX_VERSION {
                let message = make_message(v);
                roundtrip(name, &message, v);
            }
        }
    }
}
