// AUTO-GENERATED by crabka-protocol-codegen against a9ce3221537b8653448750697915607dc7936cf3. Do not edit.
// Clippy lints that fire on generated code patterns are suppressed here so
// that regenerating the file does not require manual allow annotations.
include!(concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/generated/FetchResponse.owned.rs"
));
#[path = "fetch_response_plan.rs"]
mod plan;
pub use plan::FetchWriteOp;
#[cfg(test)]
mod tests {
    use bytes::BytesMut;

    use super::*;
    use crate::{Decode, Encode};
    fn roundtrip(case: &str, msg: &FetchResponse, v: i16) {
        let mut buf = BytesMut::new();
        msg.encode(&mut buf, v).unwrap();
        assert2::assert!(msg.encoded_len(v) == buf.len(), "case {case}, version {v}");
        let bytes = buf.freeze();
        let mut cur = &bytes[..];
        let decoded = FetchResponse::decode(&mut cur, v).unwrap();
        assert2::assert!(cur.is_empty(), "case {case}, version {v}");
        let mut reencoded = BytesMut::new();
        decoded.encode(&mut reencoded, v).unwrap();
        assert2::assert!(&reencoded[..] == &bytes[..]);
        let _ = default_json(v);
    }
    #[test]
    fn roundtrip_cases_all_versions() {
        for v in MIN_VERSION..=MAX_VERSION {
            for (case, msg) in [
                ("default", FetchResponse::default()),
                ("populated", FetchResponse::populated(v)),
            ] {
                roundtrip(case, &msg, v);
            }
        }
    }
}
