// AUTO-GENERATED by crabka-protocol-codegen against a9ce3221537b8653448750697915607dc7936cf3. Do not edit.
include!(concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/generated/ProducerIdsRecord.owned.rs"
));

#[cfg(test)]
mod tests {
    use assert2::assert;
    use bytes::BytesMut;

    use super::*;
    use crate::{Decode, Encode};

    fn roundtrip(msg: &ProducerIdsRecord, version: i16) {
        let mut bytes = BytesMut::new();
        msg.encode(&mut bytes, version).unwrap();
        let mut input = &bytes[..];
        let decoded = ProducerIdsRecord::decode(&mut input, version).unwrap();
        assert!(input.is_empty());
        assert!(decoded == *msg);
    }

    #[test]
    fn all_versions_roundtrip() {
        for version in MIN_VERSION..=MAX_VERSION {
            roundtrip(&ProducerIdsRecord::default(), version);
            roundtrip(&ProducerIdsRecord::populated(version), version);
        }
    }
}
