// AUTO-GENERATED by crabka-protocol-codegen against a9ce3221537b8653448750697915607dc7936cf3. Do not edit.
#![doc = " Borrowed common structs, scoped per owning message schema."]
pub mod add_partitions_to_txn_request;
pub mod add_partitions_to_txn_response;
pub mod consumer_group_describe_response;
pub mod consumer_group_heartbeat_response;
pub mod describe_quorum_response;
pub mod leader_change_message;
pub mod share_group_describe_response;
pub mod share_group_heartbeat_response;
pub mod streams_group_describe_response;
pub mod streams_group_heartbeat_request;
pub mod streams_group_heartbeat_response;
