// AUTO-GENERATED by crabka-protocol-codegen against a9ce3221537b8653448750697915607dc7936cf3. Do not edit.
//! Borrowed common structs shared across multiple message schemas.

pub mod add_partitions_to_txn_partition_result;
pub mod add_partitions_to_txn_topic;
pub mod add_partitions_to_txn_topic_result;
pub mod assignment;
pub mod endpoint;
pub mod key_value;
pub mod replica_state;
pub mod status;
pub mod task_ids;
pub mod task_offset;
pub mod topic_info;
pub mod topic_partition;
pub mod topic_partitions;
pub mod voter;
