//! SQL sequences on a substrate-backed engine, `PersistMode::Replicated`.
//!
//! The tests cover `nextval`, `setval`, `SERIAL`, and
//! `GENERATED … AS IDENTITY`. In this mode an advance cannot go straight to the
//! applied store and must ride a commit batch.
//!
//! The centre of this file is the failover invariant: no value a writer handed
//! to a client may be issued again by its successor. The in-batch cache, name
//! reuse, `setval`, and rollback are behaviour verified against
//! `postgres:18.4`. The tests assert them here in both persistence modes,
//! because the two must not disagree about what a sequence does.

use std::sync::{
    Arc,
    atomic::{AtomicBool, Ordering},
};

use assert2::assert;
use bytes::Bytes;
use crabka_pgexec::{Committer, ExecError, Linearizer, SqlEngine};
use crabka_pgkv::{Kv, MemKv, WriteOp};
use crabka_pgwire::engine::{Engine, QueryResult, Session};

/// Commits straight to a shared in-memory KV, and stands in for the substrate
/// committer.
///
/// `accepting` models a writer that has lost its lease. The committer refuses
/// the batch, so nothing it carried becomes durable.
struct MemCommitter {
    kv: Arc<dyn Kv>,
    accepting: Arc<AtomicBool>,
}

#[async_trait::async_trait]
impl Committer for MemCommitter {
    async fn commit(&self, ops: Vec<WriteOp>) -> Result<(), ExecError> {
        if !self.accepting.load(Ordering::SeqCst) {
            return Err(ExecError::NotLeader);
        }
        self.kv.write_batch(&ops)?;
        Ok(())
    }
}

struct HealthyLeader;
#[async_trait::async_trait]
impl Linearizer for HealthyLeader {
    async fn ensure_readable(&self) -> Result<(), ExecError> {
        Ok(())
    }
}

/// A replicated engine over `kv`, plus the switch that decides whether its
/// committer still accepts batches.
fn replicated_on(kv: &Arc<dyn Kv>) -> (SqlEngine, Arc<AtomicBool>) {
    let accepting = Arc::new(AtomicBool::new(true));
    let engine = SqlEngine::replicated(
        Arc::clone(kv),
        Arc::clone(kv),
        Arc::new(MemCommitter {
            kv: Arc::clone(kv),
            accepting: Arc::clone(&accepting),
        }),
        Arc::new(HealthyLeader),
    )
    .expect("replicated engine");
    (engine, accepting)
}

fn replicated() -> (Arc<dyn Kv>, SqlEngine, Arc<AtomicBool>) {
    let kv: Arc<dyn Kv> = Arc::new(MemKv::new());
    let (engine, accepting) = replicated_on(&kv);
    (kv, engine, accepting)
}

async fn run(session: &mut crabka_pgexec::SqlSession, sql: &str) {
    session.simple_query(sql).await.expect(sql);
}

/// Every value in the first column, as text.
async fn column(session: &mut crabka_pgexec::SqlSession, sql: &str) -> Vec<String> {
    let mut results = session.simple_query(sql).await.expect(sql);
    match results.remove(0) {
        QueryResult::Rows { rows, .. } => rows
            .iter()
            .map(|row| {
                let cell = row[0].as_ref().expect("not null");
                String::from_utf8(cell.text.to_vec()).expect("utf8")
            })
            .collect(),
        other => panic!("expected Rows, got {other:?}"),
    }
}

async fn scalar(session: &mut crabka_pgexec::SqlSession, sql: &str) -> String {
    let mut values = column(session, sql).await;
    assert!(values.len() == 1, "{sql} returned {} rows", values.len());
    values.remove(0)
}

/// Both persistence modes, so each test below asserts a behaviour for the
/// in-process engine and for the substrate-backed engine alike.
enum Mode {
    Durable,
    Replicated,
}

fn engine_for(mode: &Mode) -> SqlEngine {
    match mode {
        Mode::Durable => SqlEngine::new(),
        Mode::Replicated => replicated().1,
    }
}

// ---------------------------------------------------------------------------
// The failover invariant
// ---------------------------------------------------------------------------

/// The correctness centre: a successor writer must never re-issue a value its
/// predecessor already handed to a client.
///
/// The predecessor advances a sequence through every shape that can advance
/// one: a bare `nextval`, an identity `INSERT`, and a multi-row `INSERT`. Then
/// it dies. A new engine over the same applied store stands in for the new
/// writer. Its `SequenceManager` is fresh, so it re-seeds from the store, and
/// every value it hands out must be strictly greater than everything the
/// predecessor issued.
#[tokio::test]
async fn a_successor_writer_never_reissues_a_value_its_predecessor_handed_out() {
    let (kv, engine, _accepting) = replicated();
    let mut before = engine.connect();
    run(&mut before, "CREATE SEQUENCE s").await;
    run(
        &mut before,
        "CREATE TABLE t (a int4 GENERATED BY DEFAULT AS IDENTITY, b text)",
    )
    .await;

    let mut issued: Vec<i64> = Vec::new();
    issued.push(
        scalar(&mut before, "SELECT nextval('s')")
            .await
            .parse()
            .expect("int"),
    );
    run(&mut before, "INSERT INTO t (b) VALUES ('one')").await;
    run(
        &mut before,
        "INSERT INTO t (b) VALUES ('two'),('three'),('four')",
    )
    .await;
    issued.push(
        scalar(&mut before, "SELECT nextval('s')")
            .await
            .parse()
            .expect("int"),
    );
    let identity_before: Vec<String> = column(&mut before, "SELECT a FROM t ORDER BY a").await;

    // The writer dies here. Only what reached the applied store survives.
    drop(before);
    drop(engine);

    let (successor, _accepting) = replicated_on(&kv);
    successor
        .reseed_counters()
        .expect("reseed on becoming writer");
    let mut after = successor.connect();
    let resumed: i64 = scalar(&mut after, "SELECT nextval('s')")
        .await
        .parse()
        .expect("int");
    assert!(
        resumed > *issued.iter().max().expect("issued"),
        "successor reissued {resumed}, already handed out {issued:?}"
    );

    run(&mut after, "INSERT INTO t (b) VALUES ('five')").await;
    let identity_after = column(&mut after, "SELECT a FROM t ORDER BY a").await;
    let mut sorted = identity_after.clone();
    sorted.sort_unstable();
    sorted.dedup();
    assert!(
        sorted.len() == identity_after.len(),
        "successor duplicated an identity value: {identity_after:?} (predecessor had {identity_before:?})"
    );
}

/// `reseed_counters` on a live engine is the same event without the process
/// restart, and must not walk a sequence backwards.
#[tokio::test]
async fn reseeding_a_live_engine_does_not_rewind_a_sequence() {
    let (_kv, engine, _accepting) = replicated();
    let mut session = engine.connect();
    run(&mut session, "CREATE SEQUENCE s").await;
    let before: i64 = scalar(&mut session, "SELECT nextval('s')")
        .await
        .parse()
        .expect("int");
    engine.reseed_counters().expect("reseed");
    let after: i64 = scalar(&mut session, "SELECT nextval('s')")
        .await
        .parse()
        .expect("int");
    assert!(after > before, "reseed rewound {before} -> {after}");
}

/// A value is only safe to re-issue if it never reached a client. When the
/// commit that would have recorded an advance is refused, the statement fails,
/// so no value escapes, and the successor may legitimately start over.
#[tokio::test]
async fn a_refused_commit_returns_no_value_to_the_client() {
    let (kv, engine, accepting) = replicated();
    let mut session = engine.connect();
    run(&mut session, "CREATE SEQUENCE s").await;

    accepting.store(false, Ordering::SeqCst);
    let refused = session.simple_query("SELECT nextval('s')").await;
    assert!(
        refused.is_err(),
        "a nextval whose advance cannot be committed must not return a value"
    );

    // The successor starts from the applied store, which never saw an advance.
    drop(session);
    drop(engine);
    let (successor, _accepting) = replicated_on(&kv);
    successor.reseed_counters().expect("reseed");
    let mut after = successor.connect();
    assert!(scalar(&mut after, "SELECT nextval('s')").await == "1");
}

// ---------------------------------------------------------------------------
// The in-batch cache
// ---------------------------------------------------------------------------

/// Successive advances inside one uncommitted statement must come from the
/// cache. The applied store still holds the pre-statement record, so a manager
/// that re-read it every time would hand the same value out for every row.
#[tokio::test]
async fn successive_advances_within_one_batch_are_distinct_and_increasing() {
    for mode in [Mode::Durable, Mode::Replicated] {
        let engine = engine_for(&mode);
        let mut session = engine.connect();
        run(
            &mut session,
            "CREATE TABLE t (a int4 GENERATED BY DEFAULT AS IDENTITY, b text)",
        )
        .await;
        run(
            &mut session,
            "INSERT INTO t (b) VALUES ('p'),('q'),('r'),('s')",
        )
        .await;
        assert!(column(&mut session, "SELECT a FROM t ORDER BY a").await == ["1", "2", "3", "4"]);

        run(&mut session, "CREATE SEQUENCE s").await;
        assert!(
            column(
                &mut session,
                "SELECT nextval('s') FROM generate_series(1, 3)"
            )
            .await
                == ["1", "2", "3"]
        );
    }
}

// ---------------------------------------------------------------------------
// Cache invalidation
// ---------------------------------------------------------------------------

/// `DROP SEQUENCE s; CREATE SEQUENCE s;` is a new sequence under an old name. A
/// cache entry that outlived the drop would keep advancing the dead one.
#[tokio::test]
async fn recreating_a_dropped_sequence_under_the_same_name_starts_over() {
    for mode in [Mode::Durable, Mode::Replicated] {
        let engine = engine_for(&mode);
        let mut session = engine.connect();
        run(&mut session, "CREATE SEQUENCE s").await;
        assert!(scalar(&mut session, "SELECT nextval('s')").await == "1");
        assert!(scalar(&mut session, "SELECT nextval('s')").await == "2");
        run(&mut session, "DROP SEQUENCE s").await;
        run(&mut session, "CREATE SEQUENCE s").await;
        assert!(scalar(&mut session, "SELECT nextval('s')").await == "1");
    }
}

/// The same reuse through the implicit sequence of a `SERIAL` column.
///
/// Neither `CREATE TABLE` nor `DROP SEQUENCE` spells that sequence the same way
/// the cache key does. The invalidation must therefore come off the committed
/// batch and not off the DDL text. If it does not, the recreated table keeps
/// advancing the dead sequence.
///
/// The test drops the sequence explicitly because Gres does not track `SERIAL`
/// sequence ownership, so `DROP TABLE` alone leaves `t_a_seq` behind. See the
/// same gap behind `TRUNCATE … RESTART IDENTITY`. `PostgreSQL` drops the
/// sequence with the table. That divergence is not this test's subject.
#[tokio::test]
async fn recreating_a_serial_table_restarts_its_implicit_sequence() {
    for mode in [Mode::Durable, Mode::Replicated] {
        let engine = engine_for(&mode);
        let mut session = engine.connect();
        run(&mut session, "CREATE TABLE t (a serial, b text)").await;
        run(&mut session, "INSERT INTO t (b) VALUES ('x'),('y')").await;
        assert!(column(&mut session, "SELECT a FROM t ORDER BY a").await == ["1", "2"]);
        run(&mut session, "DROP TABLE t").await;
        run(&mut session, "DROP SEQUENCE t_a_seq").await;
        run(&mut session, "CREATE TABLE t (a serial, b text)").await;
        run(&mut session, "INSERT INTO t (b) VALUES ('z')").await;
        assert!(column(&mut session, "SELECT a FROM t ORDER BY a").await == ["1"]);
    }
}

/// `setval` repositions the sequence for the next `nextval`, in both the
/// `is_called` shapes `PostgreSQL` defines.
#[tokio::test]
async fn setval_repositions_the_sequence() {
    for mode in [Mode::Durable, Mode::Replicated] {
        let engine = engine_for(&mode);
        let mut session = engine.connect();
        run(&mut session, "CREATE SEQUENCE s").await;
        assert!(scalar(&mut session, "SELECT nextval('s')").await == "1");
        // Two-argument setval marks the value consumed: the next one follows it.
        assert!(scalar(&mut session, "SELECT setval('s', 50)").await == "50");
        assert!(scalar(&mut session, "SELECT nextval('s')").await == "51");
        // `is_called => false` makes the value itself the next one handed out.
        assert!(scalar(&mut session, "SELECT setval('s', 100, false)").await == "100");
        assert!(scalar(&mut session, "SELECT nextval('s')").await == "100");
        assert!(scalar(&mut session, "SELECT nextval('s')").await == "101");
    }
}

// ---------------------------------------------------------------------------
// nextval is not transactional
// ---------------------------------------------------------------------------

/// `PostgreSQL` does not roll `nextval` back.
///
/// On `postgres:18.4`, an advance, then a rollback, then a second advance gives
/// 1 and then 3. The burned 2 is a normal gap. The replicated path folds the
/// advance into the abort batch to keep that true.
#[tokio::test]
async fn a_rolled_back_transaction_still_burns_its_sequence_values() {
    for mode in [Mode::Durable, Mode::Replicated] {
        let engine = engine_for(&mode);
        let mut session = engine.connect();
        run(&mut session, "CREATE SEQUENCE s").await;
        assert!(scalar(&mut session, "SELECT nextval('s')").await == "1");
        run(&mut session, "BEGIN").await;
        assert!(scalar(&mut session, "SELECT nextval('s')").await == "2");
        run(&mut session, "ROLLBACK").await;
        assert!(scalar(&mut session, "SELECT nextval('s')").await == "3");
    }
}

/// The same for an identity `INSERT`: the rows go, the sequence gap stays.
#[tokio::test]
async fn a_rolled_back_insert_keeps_the_identity_values_it_consumed() {
    for mode in [Mode::Durable, Mode::Replicated] {
        let engine = engine_for(&mode);
        let mut session = engine.connect();
        run(
            &mut session,
            "CREATE TABLE t (a int4 GENERATED BY DEFAULT AS IDENTITY, b text)",
        )
        .await;
        run(&mut session, "INSERT INTO t (b) VALUES ('kept')").await;
        run(&mut session, "BEGIN").await;
        run(&mut session, "INSERT INTO t (b) VALUES ('rolled back')").await;
        run(&mut session, "ROLLBACK").await;
        run(&mut session, "INSERT INTO t (b) VALUES ('after')").await;
        assert!(
            column(&mut session, "SELECT a FROM t ORDER BY a").await == ["1", "3"],
            "the aborted INSERT must leave its gap behind"
        );
    }
}

// ---------------------------------------------------------------------------
// A supplied value does not consume one
// ---------------------------------------------------------------------------

/// `PostgreSQL` advances a sequence only for a column it actually defaults.
/// Verified on `postgres:18.4` for all three spellings: insert `'one'`, then an
/// explicit `100`, then `'three'`, and the generated values are 1 and 2, never
/// 1 and 3.
#[tokio::test]
async fn an_explicitly_supplied_value_does_not_consume_a_sequence_value() {
    let forms = [
        (
            "generated by default as identity",
            "CREATE TABLE t (a int4 GENERATED BY DEFAULT AS IDENTITY, b text)",
        ),
        (
            "generated always as identity",
            "CREATE TABLE t (a int4 GENERATED ALWAYS AS IDENTITY, b text)",
        ),
        ("serial", "CREATE TABLE t (a serial, b text)"),
    ];
    for mode in [Mode::Durable, Mode::Replicated] {
        for (label, ddl) in &forms {
            let engine = engine_for(&mode);
            let mut session = engine.connect();
            run(&mut session, ddl).await;
            run(&mut session, "INSERT INTO t (b) VALUES ('one')").await;
            run(
                &mut session,
                "INSERT INTO t (a, b) VALUES (100, 'explicit')",
            )
            .await;
            run(&mut session, "INSERT INTO t (b) VALUES ('three')").await;
            assert!(
                column(&mut session, "SELECT a FROM t ORDER BY a").await == ["1", "2", "100"],
                "{label}: the explicit insert must not burn a value"
            );
        }
    }
}

/// The choice is per row and per column, not per statement. Within one
/// multi-row `VALUES`, only the rows that wrote `DEFAULT` advance, and a
/// supplied identity column does not stop a second identity column in the same
/// row from an advance. Both facts are verified on `postgres:18.4`.
#[tokio::test]
async fn defaults_are_consumed_per_row_and_per_column() {
    for mode in [Mode::Durable, Mode::Replicated] {
        let engine = engine_for(&mode);
        let mut session = engine.connect();

        run(
            &mut session,
            "CREATE TABLE mixed (a int4 GENERATED BY DEFAULT AS IDENTITY, b text)",
        )
        .await;
        run(
            &mut session,
            "INSERT INTO mixed (a, b) VALUES (100,'p'), (DEFAULT,'q'), (200,'r'), (DEFAULT,'s')",
        )
        .await;
        assert!(
            column(&mut session, "SELECT a FROM mixed ORDER BY b").await
                == ["100", "1", "200", "2"],
            "only the DEFAULT rows advance"
        );

        run(
            &mut session,
            "CREATE TABLE two (a int4 GENERATED BY DEFAULT AS IDENTITY, \
             c int4 GENERATED BY DEFAULT AS IDENTITY, b text)",
        )
        .await;
        run(&mut session, "INSERT INTO two (b) VALUES ('one')").await;
        run(
            &mut session,
            "INSERT INTO two (a, b) VALUES (100, 'explicit')",
        )
        .await;
        run(&mut session, "INSERT INTO two (b) VALUES ('three')").await;
        assert!(column(&mut session, "SELECT a FROM two ORDER BY b").await == ["100", "1", "2"]);
        assert!(
            column(&mut session, "SELECT c FROM two ORDER BY b").await == ["2", "1", "3"],
            "the column that was not supplied still advances"
        );
    }
}

/// `COPY` follows the same rule: a column in the column list is supplied, even
/// when its value is the NULL marker, and only a column outside the list takes
/// its default. Verified on `postgres:18.4`.
#[tokio::test]
async fn copy_only_defaults_the_columns_outside_its_column_list() {
    for mode in [Mode::Durable, Mode::Replicated] {
        let engine = engine_for(&mode);
        let mut session = engine.connect();
        run(
            &mut session,
            "CREATE TABLE t (a int4 GENERATED BY DEFAULT AS IDENTITY, b text)",
        )
        .await;
        session
            .copy_in(
                "COPY t (a, b) FROM STDIN",
                0,
                vec![Bytes::from_static(b"500\tx\n501\ty\n")],
            )
            .await
            .expect("copy with explicit ids");
        session
            .copy_in("COPY t (b) FROM STDIN", 0, vec![Bytes::from_static(b"z\n")])
            .await
            .expect("copy defaulting the identity");
        assert!(column(&mut session, "SELECT a FROM t ORDER BY a").await == ["1", "500", "501"]);
    }
}
