// AUTO-GENERATED by crabka-protocol-codegen against b25e89b6f842f11e4eb747e131a71153d9270536. Do not edit.
#![doc = " Owned (heap-allocated) message types."]
#![allow(unused_imports, unused_mut, unused_variables)]
pub mod fetch_request;
pub mod fetch_response;
pub mod produce_request;
pub mod produce_response;
