// AUTO-GENERATED by crabka-protocol-codegen against b25e89b6f842f11e4eb747e131a71153d9270536. Do not edit.
// Clippy lints that fire on generated code patterns are suppressed here so
// that regenerating the file does not require manual allow annotations.
include!(concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/generated/kafka_3_6_2/ProduceResponse.owned.rs"
));
#[cfg(test)]
mod tests {
    use bytes::BytesMut;

    use super::*;
    use crate::{Decode, Encode};
    fn roundtrip(case: &str, msg: &ProduceResponse, v: i16) {
        let mut buf = BytesMut::new();
        msg.encode(&mut buf, v).unwrap();
        assert2::assert!(msg.encoded_len(v) == buf.len(), "case {case}, version {v}");
        let bytes = buf.freeze();
        let mut cur = &bytes[..];
        let decoded = ProduceResponse::decode(&mut cur, v).unwrap();
        assert2::assert!(cur.is_empty(), "case {case}, version {v}");
        let mut reencoded = BytesMut::new();
        decoded.encode(&mut reencoded, v).unwrap();
        assert2::assert!(&reencoded[..] == &bytes[..]);
        let _ = default_json(v);
    }
    #[test]
    fn roundtrip_cases_all_versions() {
        for v in MIN_VERSION..=MAX_VERSION {
            for (case, msg) in [
                ("default", ProduceResponse::default()),
                ("populated", ProduceResponse::populated(v)),
            ] {
                roundtrip(case, &msg, v);
            }
        }
    }
}
