{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "crabka-schema-registry.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "crabka-schema-registry.labels" . | nindent 4 }}
{{- end }}
