apiVersion: v1
kind: Service
metadata:
  name: {{ include "crabka-schema-registry.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "crabka-schema-registry.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: rest
      protocol: TCP
      name: rest
  selector: {{- include "crabka-schema-registry.selectorLabels" . | nindent 4 }}
