{{- if and .Values.caRenewal.enabled .Values.rbac.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "crabka-operator.fullname" . }}-ca-renewal
  labels: {{- include "crabka-operator.labels" . | nindent 4 }}
{{- end }}
