apiVersion: v1
kind: Service
metadata:
  name: {{ include "crabka-operator.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "crabka-operator.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector: {{- include "crabka-operator.selectorLabels" . | nindent 4 }}
