[package]
name = "crabka-telemetry"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
rust-version.workspace = true
description = "Generic OTLP distributed-tracing pipeline for Crabka services"
repository = "https://github.com/robot-head/crabka"
homepage = "https://github.com/robot-head/crabka"
documentation = "https://docs.rs/crabka-telemetry"
readme = "README.md"
keywords = ["kafka", "otlp", "tracing", "telemetry", "crabka"]
categories = ["development-tools::debugging"]

[lints]
workspace = true

[dependencies]
crabka-logfmt = { version = "0.3.8", path = "../logfmt" }
opentelemetry = { workspace = true, features = ["trace"] }
opentelemetry_sdk = { workspace = true, features = ["trace"] }
opentelemetry-otlp = { workspace = true, features = ["trace", "grpc-tonic", "http-proto", "reqwest-blocking-client"] }
tracing-opentelemetry = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true, features = ["env-filter"] }
thiserror = { workspace = true }

[dev-dependencies]
assert2 = { workspace = true }
