-- D4/D7: CREATE TABLE breadth, diffed against PostgreSQL 18.4.
-- IF NOT EXISTS, `(LIKE source …)`, empty column lists, named table
-- constraints, GENERATED … AS IDENTITY, GENERATED ALWAYS AS (…) STORED,
-- CREATE INDEX options, and COMMENT ON.
-- The harness runs every statement over ONE connection, so state accumulates.
CREATE TABLE ctb_base (id int4 PRIMARY KEY, v text NOT NULL, w text);
INSERT INTO ctb_base VALUES (1, 'a', 'b');
SELECT id, v, w FROM ctb_base;
-- IF NOT EXISTS makes a duplicate name a no-op instead of 42P07.
CREATE TABLE ctb_base (id int4);
CREATE TABLE IF NOT EXISTS ctb_base (id int4);
SELECT id, v, w FROM ctb_base;
-- LIKE copies the column list; NOT NULL rides along, DEFAULT/indexes do not.
CREATE TABLE ctb_like (LIKE ctb_base);
INSERT INTO ctb_like VALUES (1, 'x', NULL);
INSERT INTO ctb_like VALUES (1, 'y', NULL);
INSERT INTO ctb_like VALUES (2, NULL, NULL);
SELECT id, v, w FROM ctb_like ORDER BY id, v;
CREATE TABLE ctb_like_all (LIKE ctb_base INCLUDING ALL);
INSERT INTO ctb_like_all VALUES (1, 'x', NULL);
INSERT INTO ctb_like_all VALUES (1, 'y', NULL);
SELECT id, v, w FROM ctb_like_all ORDER BY id;
CREATE TABLE ctb_like_missing (LIKE ctb_nope);
-- LIKE with explicit columns added after it.
CREATE TABLE ctb_like_extra (LIKE ctb_base, extra int4 DEFAULT 9);
INSERT INTO ctb_like_extra (id, v) VALUES (1, 'q');
SELECT id, v, w, extra FROM ctb_like_extra;
-- An empty column list is legal.
CREATE TABLE ctb_empty ();
SELECT count(*) FROM ctb_empty;
-- Named table constraints and default constraint names.
CREATE TABLE ctb_named (a int4, b int4, CONSTRAINT ctb_u UNIQUE (a, b), CONSTRAINT ctb_pk PRIMARY KEY (a));
INSERT INTO ctb_named VALUES (1, 1);
INSERT INTO ctb_named VALUES (1, 2);
INSERT INTO ctb_named VALUES (2, 1);
INSERT INTO ctb_named VALUES (2, 1);
SELECT a, b FROM ctb_named ORDER BY a, b;
ALTER TABLE ctb_named DROP CONSTRAINT ctb_u;
INSERT INTO ctb_named VALUES (3, 1);
SELECT a, b FROM ctb_named ORDER BY a, b;
-- GENERATED … AS IDENTITY.
CREATE TABLE ctb_id (a int4 GENERATED BY DEFAULT AS IDENTITY, b text);
INSERT INTO ctb_id (b) VALUES ('one');
INSERT INTO ctb_id (b) VALUES ('two');
SELECT a, b FROM ctb_id ORDER BY a;
INSERT INTO ctb_id (a, b) VALUES (100, 'explicit');
SELECT a, b FROM ctb_id ORDER BY a;
CREATE TABLE ctb_id2 (a int4 GENERATED ALWAYS AS IDENTITY (START WITH 10 INCREMENT BY 5), b text);
INSERT INTO ctb_id2 (b) VALUES ('one');
INSERT INTO ctb_id2 (b) VALUES ('two');
SELECT a, b FROM ctb_id2 ORDER BY a;
-- GENERATED ALWAYS AS (expr) STORED.
CREATE TABLE ctb_gen (a int4, doubled int4 GENERATED ALWAYS AS (a * 2) STORED);
INSERT INTO ctb_gen (a) VALUES (3);
INSERT INTO ctb_gen (a) VALUES (NULL);
SELECT a, doubled FROM ctb_gen ORDER BY a NULLS LAST;
UPDATE ctb_gen SET a = 10 WHERE a = 3;
SELECT a, doubled FROM ctb_gen ORDER BY a NULLS LAST;
DELETE FROM ctb_gen;
CREATE TABLE ctb_gen2 (a int4, b int4, total int4 GENERATED ALWAYS AS (a + b) STORED, CHECK (total < 100));
INSERT INTO ctb_gen2 (a, b) VALUES (1, 2);
INSERT INTO ctb_gen2 (a, b) VALUES (60, 60);
SELECT a, b, total FROM ctb_gen2 ORDER BY a;
-- CREATE INDEX options.
CREATE TABLE ctb_idx (a int4, b text, c int4);
INSERT INTO ctb_idx VALUES (1, 'x', 10), (2, 'y', 20), (3, 'x', 30);
CREATE INDEX ctb_idx_a ON ctb_idx (a);
CREATE INDEX ctb_idx_a ON ctb_idx (a);
CREATE INDEX IF NOT EXISTS ctb_idx_a ON ctb_idx (a);
CREATE INDEX ctb_idx_bc ON ctb_idx USING btree (b, c);
CREATE UNIQUE INDEX ctb_idx_u ON ctb_idx (c);
INSERT INTO ctb_idx VALUES (4, 'z', 10);
SELECT a, b, c FROM ctb_idx ORDER BY a;
SELECT a, b, c FROM ctb_idx WHERE b = 'x' ORDER BY a;
SELECT a, b, c FROM ctb_idx WHERE c = 20;
DROP INDEX ctb_idx_u;
INSERT INTO ctb_idx VALUES (4, 'z', 10);
SELECT a, b, c FROM ctb_idx ORDER BY a, c;
DROP INDEX ctb_idx_a;
DROP INDEX ctb_idx_a;
DROP INDEX IF EXISTS ctb_idx_a;
-- COMMENT ON.
COMMENT ON TABLE ctb_idx IS 'index playground';
COMMENT ON COLUMN ctb_idx.a IS 'the a column';
COMMENT ON TABLE ctb_idx IS NULL;
COMMENT ON INDEX ctb_idx_bc IS 'multicolumn';
COMMENT ON TABLE ctb_nope IS 'x';
COMMENT ON COLUMN ctb_idx.nope IS 'x';
SELECT count(*) FROM ctb_idx;
DROP TABLE ctb_idx;
DROP TABLE ctb_gen2;
DROP TABLE ctb_gen;
DROP TABLE ctb_id2;
DROP TABLE ctb_id;
DROP TABLE ctb_named;
DROP TABLE ctb_empty;
DROP TABLE ctb_like_extra;
DROP TABLE ctb_like_all;
DROP TABLE ctb_like;
DROP TABLE ctb_base;
DROP TABLE ctb_base;
DROP TABLE IF EXISTS ctb_base;
-- Constraint-name collisions inside one CREATE TABLE.
CREATE TABLE ctc_dup (a int4, CONSTRAINT ctc_d CHECK (a > 0), CONSTRAINT ctc_d CHECK (a < 5));
CREATE TABLE ctc_gen (a int4 CHECK (a > 0), CONSTRAINT ctc_gen_a_check CHECK (a < 100));
CREATE TABLE ctc_gen2 (a int4, CONSTRAINT ctc_gen2_a_check CHECK (a < 100), CHECK (a > 0));
SELECT conname FROM pg_constraint WHERE conname LIKE 'ctc_gen2%' ORDER BY conname;
INSERT INTO ctc_gen2 VALUES (0);
INSERT INTO ctc_gen2 VALUES (100);
INSERT INTO ctc_gen2 VALUES (5);
SELECT a FROM ctc_gen2;
DROP TABLE ctc_gen2;
-- A generated column may not read another generated column, an unknown column,
-- or an aggregate.
CREATE TABLE ctc_g1 (a int4, b int4 GENERATED ALWAYS AS (a + 1) STORED, c int4 GENERATED ALWAYS AS (b + 1) STORED);
CREATE TABLE ctc_g2 (a int4, b int4 GENERATED ALWAYS AS (nope + 1) STORED);
CREATE TABLE ctc_g3 (a int4, b int4 GENERATED ALWAYS AS (sum(a)) STORED);
CREATE TABLE ctc_g4 (a int4, b int4 GENERATED ALWAYS AS (a + 1) STORED);
INSERT INTO ctc_g4 (a) VALUES (1);
SELECT a, b FROM ctc_g4;
DROP TABLE ctc_g4;

-- `bpchar` is PostgreSQL's own name for the blank-padded character type and is
-- accepted as a type name, carrying no implicit (1). `public` is not a keyword
-- in PostgreSQL at all, so it works as a column label.
SELECT length('ab'::bpchar), 'ab'::bpchar, upper('ab'::bpchar);
CREATE TABLE bpc (c bpchar);
INSERT INTO bpc VALUES ('xy');
SELECT c FROM bpc;
DROP TABLE bpc;
SELECT 1 AS public;
