[package]
name = "crabka-client-consumer"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
rust-version.workspace = true
description = "Subscribe-style consumer client for Apache Kafka in Rust"
repository = "https://github.com/robot-head/crabka"
homepage = "https://github.com/robot-head/crabka"
documentation = "https://docs.rs/crabka-client-consumer"
readme = "README.md"
keywords = ["kafka", "consumer", "client", "streaming", "crabka"]
categories = ["api-bindings", "network-programming"]

[lints]
workspace = true

[features]
default = []

[dependencies]
assert2 = { workspace = true }
bon = { workspace = true }
crabka-protocol = { version = "0.4.0", path = "../protocol", default-features = false }
crabka-client-core = { version = "0.4.0", path = "../client-core", features = ["mock"] }
crabka-ids = { version = "0.4.0", path = "../ids" }
crabka-units = { workspace = true }
bytes = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["rt", "rt-multi-thread", "sync", "time", "macros"] }
tracing = { workspace = true }
tokio-util = { workspace = true, features = ["rt"] }
futures-util = { workspace = true }
refined_type = { workspace = true }

[dev-dependencies]
crabka-broker = { path = "../broker", features = ["test-helpers"] }
crabka-client-producer = { path = "../client-producer" }
crabka-security = { path = "../security" }
mutants = { workspace = true }
stateright = { workspace = true }
tempfile = { workspace = true }
tokio = { workspace = true, features = ["test-util", "macros", "rt-multi-thread"] }
proptest = { workspace = true }
uuid = { workspace = true }
