[package]
name = "crabka-client-consumer"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
rust-version.workspace = true
description = "Subscribe-style consumer client for Apache Kafka in Rust"

[lints]
workspace = true

[features]
default = []

[dependencies]
bon = { workspace = true }
crabka-protocol = { version = "0.3", path = "../protocol", default-features = false }
crabka-client-core = { version = "0.3", path = "../client-core" }
bytes = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["rt", "rt-multi-thread", "sync", "time", "macros"] }
tracing = { workspace = true }
tokio-util = { workspace = true, features = ["rt"] }
futures-util = { workspace = true }

[dev-dependencies]
assert2 = { workspace = true }
crabka-security = { version = "0.3", path = "../security" }
tempfile = { workspace = true }
tokio = { workspace = true, features = ["test-util", "macros"] }
proptest = { workspace = true }
uuid = { workspace = true }
