// AUTO-GENERATED by crabka-protocol-codegen against a9ce3221537b8653448750697915607dc7936cf3. Do not edit.
include!(concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/generated/common/borrowed/add_partitions_to_txn_request/add_partitions_to_txn_topic.borrowed.rs"
));
