// AUTO-GENERATED by crabka-protocol-codegen against a9ce3221537b8653448750697915607dc7936cf3. Do not edit.
// Clippy lints that fire on generated code patterns are suppressed here so
// that regenerating the file does not require manual allow annotations.
#![allow(
    clippy::absurd_extreme_comparisons,
    clippy::cast_possible_truncation,
    clippy::cast_possible_wrap,
    clippy::cast_sign_loss,
    clippy::default_trait_access,
    clippy::must_use_candidate,
    clippy::new_without_default,
    clippy::nonminimal_bool,
    clippy::too_many_lines,
    clippy::unnecessary_wraps,
    clippy::unreadable_literal,
    unused_mut,
    unused_variables
)]

include!(concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/generated/ListOffsetsRequest.borrowed.rs"
));
#[cfg(test)]
mod tests {
    use assert2::assert;
    use bytes::BytesMut;

    use super::*;
    use crate::{DecodeBorrow, Encode};
    #[test]
    fn roundtrips_all_versions() {
        for v in MIN_VERSION..=MAX_VERSION {
            let cases = [
                ("default", ListOffsetsRequest::default()),
                ("populated", ListOffsetsRequest::populated(v)),
            ];

            for (case, expected) in cases {
                let mut encoded = BytesMut::new();
                expected.encode(&mut encoded, v).unwrap();
                let msg_bytes = encoded.freeze();
                let mut cur: &[u8] = &msg_bytes;
                let decoded = ListOffsetsRequest::decode_borrow(&mut cur, v).unwrap();

                assert!(cur.is_empty(), "{case} at version {v}");
                assert!(decoded == expected, "{case} at version {v}");
                assert!(
                    decoded.encoded_len(v) == msg_bytes.len(),
                    "{case} at version {v}"
                );

                let mut reencoded = BytesMut::new();
                decoded.encode(&mut reencoded, v).unwrap();
                assert!(&reencoded[..] == &msg_bytes[..], "{case} at version {v}");

                let owned = decoded.to_owned();
                let mut owned_buf = BytesMut::new();
                owned.encode(&mut owned_buf, v).unwrap();
                assert!(&owned_buf[..] == &msg_bytes[..], "{case} at version {v}");
            }
        }
    }
}
