// AUTO-GENERATED by crabka-protocol-codegen against a9ce3221537b8653448750697915607dc7936cf3. Do not edit.
include!(concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/generated/ProduceRequest.borrowed.rs"
));
#[cfg(test)]
mod tests {
    use assert2::assert;
    use bytes::BytesMut;

    use super::*;
    use crate::{DecodeBorrow, Encode};
    fn check(msg_bytes: &bytes::Bytes, v: i16) {
        let mut cur: &[u8] = msg_bytes;
        let decoded = ProduceRequest::decode_borrow(&mut cur, v).unwrap();
        assert!(cur.is_empty());
        assert!(decoded.encoded_len(v) == msg_bytes.len());
        let mut reencoded = BytesMut::new();
        decoded.encode(&mut reencoded, v).unwrap();
        assert!(&reencoded[..] == &msg_bytes[..]);
        let owned = decoded.to_owned();
        let mut owned_buf = BytesMut::new();
        owned.encode(&mut owned_buf, v).unwrap();
        assert!(&owned_buf[..] == &msg_bytes[..]);
    }
    #[test]
    fn default_roundtrips_all_versions() {
        for v in MIN_VERSION..=MAX_VERSION {
            let msg = ProduceRequest::default();
            let mut buf = BytesMut::new();
            msg.encode(&mut buf, v).unwrap();
            check(&buf.freeze(), v);
        }
    }
    #[test]
    fn populated_roundtrips_all_versions() {
        for v in MIN_VERSION..=MAX_VERSION {
            let msg = ProduceRequest::populated(v);
            let mut buf = BytesMut::new();
            msg.encode(&mut buf, v).unwrap();
            check(&buf.freeze(), v);
        }
    }
}
