// AUTO-GENERATED by crabka-protocol-codegen against a9ce3221537b8653448750697915607dc7936cf3. Do not edit.
include!(concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/generated/ProducerIdsRecord.borrowed.rs"
));

#[cfg(test)]
mod tests {
    use assert2::assert;
    use bytes::BytesMut;

    use super::*;
    use crate::{DecodeBorrow, Encode};

    #[test]
    fn all_versions_roundtrip() {
        for version in MIN_VERSION..=MAX_VERSION {
            let msg = ProducerIdsRecord::populated(version);
            let mut bytes = BytesMut::new();
            msg.encode(&mut bytes, version).unwrap();
            let mut input = &bytes[..];
            let decoded = ProducerIdsRecord::decode_borrow(&mut input, version).unwrap();
            assert!(input.is_empty());
            assert!(decoded == msg);
            assert!(decoded.to_owned().next_producer_id == msg.next_producer_id);
        }
    }
}
